/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_akhir;

import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author ChocoLava
 */
public class Detail_wisuda extends javax.swing.JFrame {
    
    public static Connection con = new koneksi().ambil_koneksi();
    /**
     * Creates new form Detail_wisuda
     */
    public Detail_wisuda() {
        initComponents();
        detail();
    }
    
    private void detail(){
        try{
            String detail_wsd = "SELECT mhs.nama_mahasiswa AS nama_mhs,\n" +
                                "mhs.Jenis_Kelamin AS jk_mhs, mhs.Agama AS agama_mhs,\n" +
                                "mhs.alamat AS almt_mhs, mhs.no_hp AS hp_mhs,\n" +
                                "mhs.Alamat_Orang_Tua AS alamat_ortu_mhs,\n" +
                                "mhs.NRP AS nrp_mhs, mhs.prodi AS prodi_mhs,\n" +
                                "mhs.email AS email_mhs, wsd.ipk AS ipk_mhs, wsd.judul_ta AS ta_mhs,\n" +
                                "wsd.bukti_pembayaran AS bukti_bayar, dsn.nama_dosen AS nama_dsn\n" +
                                "FROM Wisuda wsd\n" +
                                "INNER JOIN mahasiswa mhs ON mhs.NRP = wsd.NRP\n" +
                                "INNER JOIN Dosen dsn ON dsn.nip_dosen = wsd.nip_dosen\n" +
                                "WHERE mhs.NRP LIKE '%"+framebaa.nrp_list_wsd+"%'\n";
            ResultSet res_detail_wsd = con.prepareStatement(detail_wsd).executeQuery();
            
            if(res_detail_wsd.next()){
                lbl_tmpl_nama_wsd_mhs.setText(res_detail_wsd.getString("nama_mhs"));
                lbl_tmpl_jk_wsd_mhs.setText(res_detail_wsd.getString("jk_mhs"));
                lbl_tmpl_agama_wsd_mhs.setText(res_detail_wsd.getString("agama_mhs"));
                lbl_tmpl_almt_wsd_mhs.setText(res_detail_wsd.getString("almt_mhs"));
                lbl_tmpl_no_wsd_mhs.setText(res_detail_wsd.getString("hp_mhs"));
                lbl_tmpl_almt_ortu_wsd_mhs.setText(res_detail_wsd.getString("alamat_ortu_mhs"));
                lbl_tmpl_nrp_wsd_mhs.setText(res_detail_wsd.getString("nrp_mhs"));
                lbl_tmpl_prodi_wsd_mhs.setText(res_detail_wsd.getString("prodi_mhs"));
                lbl_email_wsd_mhs.setText(res_detail_wsd.getString("email_mhs"));
                lbl_tmpl_ipk_wsd_mhs.setText(res_detail_wsd.getString("ipk_mhs"));
                lbl_tmpl_ta_wsd_mhs.setText(res_detail_wsd.getString("ta_mhs"));
                lbl_tmpl_dsn_wsd_mhs.setText(res_detail_wsd.getString("nama_dsn"));
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tmpl_detail_wsd = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_tmpl_nama_wsd_mhs = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbl_tmpl_jk_wsd_mhs = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lbl_tmpl_agama_wsd_mhs = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lbl_tmpl_almt_wsd_mhs = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_tmpl_no_wsd_mhs = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lbl_tmpl_almt_ortu_wsd_mhs = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lbl_tmpl_nrp_wsd_mhs = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbl_tmpl_prodi_wsd_mhs = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lbl_email_wsd_mhs = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        lbl_tmpl_ipk_wsd_mhs = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        lbl_tmpl_ta_wsd_mhs = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_tmpl_dsn_wsd_mhs = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel_bukti_pembayaran = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_bukti_byr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_tmpl_detail_wsd.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail"));

        jPanel6.setLayout(new java.awt.GridLayout(6, 2, 0, 15));

        jLabel4.setText("Nama Mahasiswa");
        jPanel6.add(jLabel4);

        lbl_tmpl_nama_wsd_mhs.setText("Nama Lengkap");
        jPanel6.add(lbl_tmpl_nama_wsd_mhs);

        jLabel35.setText("Jenis Kelamin");
        jPanel6.add(jLabel35);

        lbl_tmpl_jk_wsd_mhs.setText("Jenis Kelamin");
        jPanel6.add(lbl_tmpl_jk_wsd_mhs);

        jLabel36.setText("Agama");
        jPanel6.add(jLabel36);

        lbl_tmpl_agama_wsd_mhs.setText("Agama");
        jPanel6.add(lbl_tmpl_agama_wsd_mhs);

        jLabel37.setText("Alamat");
        jPanel6.add(jLabel37);

        lbl_tmpl_almt_wsd_mhs.setText("Alamat");
        jPanel6.add(lbl_tmpl_almt_wsd_mhs);

        jLabel39.setText("No Hp");
        jPanel6.add(jLabel39);

        lbl_tmpl_no_wsd_mhs.setText("No Hp");
        jPanel6.add(lbl_tmpl_no_wsd_mhs);

        jLabel40.setText("Alamat Orang Tua");
        jPanel6.add(jLabel40);

        lbl_tmpl_almt_ortu_wsd_mhs.setText("Alamat Ortu");
        jPanel6.add(lbl_tmpl_almt_ortu_wsd_mhs);

        jPanel7.setLayout(new java.awt.GridLayout(6, 2, 0, 15));

        jLabel33.setText("NRP");
        jPanel7.add(jLabel33);

        lbl_tmpl_nrp_wsd_mhs.setText("NRP");
        jPanel7.add(lbl_tmpl_nrp_wsd_mhs);

        jLabel34.setText("Program Studi");
        jPanel7.add(jLabel34);

        lbl_tmpl_prodi_wsd_mhs.setText("Program Studi");
        jPanel7.add(lbl_tmpl_prodi_wsd_mhs);

        jLabel38.setText("Email");
        jPanel7.add(jLabel38);

        lbl_email_wsd_mhs.setText("Email");
        jPanel7.add(lbl_email_wsd_mhs);

        jLabel41.setText("IPK");
        jPanel7.add(jLabel41);

        lbl_tmpl_ipk_wsd_mhs.setText("IPK");
        jPanel7.add(lbl_tmpl_ipk_wsd_mhs);

        jLabel42.setText("Judul Tugas Akhir");
        jPanel7.add(jLabel42);

        lbl_tmpl_ta_wsd_mhs.setText("Judul Tugas Akhir");
        jPanel7.add(lbl_tmpl_ta_wsd_mhs);

        jLabel43.setText("Dosen Pembimbing");
        jPanel7.add(jLabel43);

        lbl_tmpl_dsn_wsd_mhs.setText("Dosen");
        jPanel7.add(lbl_tmpl_dsn_wsd_mhs);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_tmpl_detail_wsdLayout = new javax.swing.GroupLayout(panel_tmpl_detail_wsd);
        panel_tmpl_detail_wsd.setLayout(panel_tmpl_detail_wsdLayout);
        panel_tmpl_detail_wsdLayout.setHorizontalGroup(
            panel_tmpl_detail_wsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_detail_wsdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panel_tmpl_detail_wsdLayout.setVerticalGroup(
            panel_tmpl_detail_wsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_detail_wsdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tmpl_detail_wsdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_bukti_pembayaran.setBorder(javax.swing.BorderFactory.createTitledBorder("Bukti Pembayaran"));

        jDesktopPane1.setLayer(lbl_bukti_byr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(lbl_bukti_byr, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_bukti_byr, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_bukti_pembayaranLayout = new javax.swing.GroupLayout(panel_bukti_pembayaran);
        panel_bukti_pembayaran.setLayout(panel_bukti_pembayaranLayout);
        panel_bukti_pembayaranLayout.setHorizontalGroup(
            panel_bukti_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bukti_pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        panel_bukti_pembayaranLayout.setVerticalGroup(
            panel_bukti_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_bukti_pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_bukti_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_tmpl_detail_wsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(panel_bukti_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_tmpl_detail_wsd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(373, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail_wisuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail_wisuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail_wisuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail_wisuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail_wisuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_bukti_byr;
    private javax.swing.JLabel lbl_email_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_agama_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_almt_ortu_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_almt_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_dsn_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_ipk_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_jk_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_nama_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_no_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_nrp_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_prodi_wsd_mhs;
    private javax.swing.JLabel lbl_tmpl_ta_wsd_mhs;
    private javax.swing.JPanel panel_bukti_pembayaran;
    private javax.swing.JPanel panel_tmpl_detail_wsd;
    // End of variables declaration//GEN-END:variables
}
