/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_akhir;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class framebaa extends javax.swing.JFrame {
    public static Connection con = new koneksi().ambil_koneksi();
    
    private static String kota_dsn;
    
    //untuk mahasiswa
    private static String nrp_mhs, email_mhs, nama_mhs, prodi_mhs, agama_mhs, jk_mhs, kota_mhs, ttl_mhs, 
            almt_mhs, hp_mhs, stts_mhs;
    private static int indx_kota_mhs;
    
    //untuk orang tua
    private static String nama_ayah_mhs, ktp_ayah_mhs, nama_ibu_mhs, 
            ktp_ibu_mhs, kota_ortu_mhs, hp_ortu_mhs, alamat_ortu_mhs;
    private static int indx_kota_ortu_mhs;
    
    //untuk dosen
    private static String NIP_dsn, NIDN_dsn, Nama_dsn, Email_dsn, Alamat_dsn, Telepon_dsn, 
            Jenis_Kelamin_dsn, Tempat_Tanggal_Lahir_dsn, Pendidikan_tertinggi_dsn,status_dsn,  Jabatan_Akademik_dsn;
    /**
     * Creates new form framebaa
     */
    public framebaa() {
        initComponents();
        tampilkota();
        clear_all();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp_jk_mhs_baa = new javax.swing.ButtonGroup();
        grp_jk_dsn_baa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        title_baa = new javax.swing.JLabel();
        panelinduk_baa = new javax.swing.JPanel();
        panel_add_mhs = new javax.swing.JPanel();
        border2 = new javax.swing.JPanel();
        input_mhs = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panel_nrp = new javax.swing.JPanel();
        txt_NRP_baa = new javax.swing.JTextField();
        cb_NRP_baa = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_Email_mhs_baa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Nama_mhs_baa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbx_Prodi_baa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        pnl_jk_mhs_baa = new javax.swing.JPanel();
        rd_laki_mhs = new javax.swing.JRadioButton();
        rd_perempuan_mhs = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbx_Agama_mhs_baa = new javax.swing.JComboBox<>();
        jLabel2_dsn1 = new javax.swing.JLabel();
        txt_ttl_mhs_baa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_Alamat_mhs_baa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbx_kota_mhs_baa = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txt_nohp_mhs_baa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_Status_mhs_baa = new javax.swing.JCheckBox();
        btnadd_mhs_baa = new javax.swing.JButton();
        btn_clear_mhs_baa = new javax.swing.JButton();
        panel_add_ortu = new javax.swing.JPanel();
        border1 = new javax.swing.JPanel();
        input_ortu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtnm_ayah_baa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtktp_ayah_baa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnm_ibu_baa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtktp_ibu_baa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_alamatortu_baa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cb_kota_ortu_baa = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txt_telp_ortu_baa = new javax.swing.JTextField();
        btnadd_ortu_baa = new javax.swing.JButton();
        btn_clear_ortu_baa = new javax.swing.JButton();
        btn_back_mhs = new javax.swing.JButton();
        panel_matkul = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelMatkul = new javax.swing.JTable();
        panel_dsn = new javax.swing.JPanel();
        border = new javax.swing.JPanel();
        input_dsn = new javax.swing.JPanel();
        jLabel5_dsn = new javax.swing.JLabel();
        panelnip = new javax.swing.JPanel();
        txt_NIP_dsn_baa = new javax.swing.JTextField();
        cbx_nip_dsn_baa = new javax.swing.JComboBox<>();
        jLabel12_dsn = new javax.swing.JLabel();
        txt_NIDN_dsn_baa = new javax.swing.JTextField();
        jLabel6_dsn = new javax.swing.JLabel();
        txt_Nama_dsn_baa = new javax.swing.JTextField();
        jLabel11_dsn = new javax.swing.JLabel();
        txt_Alamat_dsn_baa = new javax.swing.JTextField();
        jLabel21_dsn = new javax.swing.JLabel();
        txt_nohp_dsn_baa = new javax.swing.JTextField();
        jLabel1_dsn = new javax.swing.JLabel();
        txt_email_dsn_baa = new javax.swing.JTextField();
        jLabel9_dsn = new javax.swing.JLabel();
        pnl_jk_dsn = new javax.swing.JPanel();
        rd_laki_dsn_baa = new javax.swing.JRadioButton();
        rd_perempuan_dsn_baa = new javax.swing.JRadioButton();
        jLabel2_dsn = new javax.swing.JLabel();
        txt_ttl_dsn_baa = new javax.swing.JTextField();
        jLabel8_dsn = new javax.swing.JLabel();
        cb_Status_dsn_baa = new javax.swing.JCheckBox();
        jLabel3_dsn = new javax.swing.JLabel();
        cb_pendidikan_dsn_baa = new javax.swing.JComboBox<>();
        jLabel7_dsn = new javax.swing.JLabel();
        cb_jbtn_dsn_baa = new javax.swing.JComboBox<>();
        btn_Ubah_dsn_baa = new javax.swing.JButton();
        btn_reset_dsn = new javax.swing.JButton();
        panel_mhs_tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_all_mahasiswa = new javax.swing.JTable();
        panel_dsn_tabel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_all_dsn = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_mhs = new javax.swing.JMenu();
        add_data_mhs = new javax.swing.JMenuItem();
        update_data_mhs = new javax.swing.JMenuItem();
        list_data_mhs = new javax.swing.JMenuItem();
        menu_dosen = new javax.swing.JMenu();
        add_data_dsn = new javax.swing.JMenuItem();
        update_data_dsn = new javax.swing.JMenuItem();
        list_data_dsn = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        title_baa.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        title_baa.setText("BAA");
        jPanel1.add(title_baa, new java.awt.GridBagConstraints());

        panelinduk_baa.setLayout(new java.awt.CardLayout());

        border2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubah Data Mahasiswa"));

        input_mhs.setLayout(new java.awt.GridLayout(11, 2, 0, 15));

        jLabel5.setText("NRP");
        input_mhs.add(jLabel5);

        txt_NRP_baa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_NRP_baaFocusLost(evt);
            }
        });

        cb_NRP_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== PILIH NRP ===" }));
        cb_NRP_baa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_NRP_baaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_nrpLayout = new javax.swing.GroupLayout(panel_nrp);
        panel_nrp.setLayout(panel_nrpLayout);
        panel_nrpLayout.setHorizontalGroup(
            panel_nrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_NRP_baa)
            .addComponent(cb_NRP_baa, 0, 247, Short.MAX_VALUE)
        );
        panel_nrpLayout.setVerticalGroup(
            panel_nrpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nrpLayout.createSequentialGroup()
                .addComponent(txt_NRP_baa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_NRP_baa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        input_mhs.add(panel_nrp);

        jLabel12.setText("Email");
        input_mhs.add(jLabel12);

        txt_Email_mhs_baa.setEditable(false);
        input_mhs.add(txt_Email_mhs_baa);

        jLabel6.setText("Nama");
        input_mhs.add(jLabel6);
        input_mhs.add(txt_Nama_mhs_baa);

        jLabel7.setText("Prodi");
        input_mhs.add(jLabel7);

        cbx_Prodi_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "> Teknik Informatika", "> Sistem Informasi", "> Manajemen Informatika", "> DKV" }));
        input_mhs.add(cbx_Prodi_baa);

        jLabel9.setText("Jenis Kelamin");
        input_mhs.add(jLabel9);

        pnl_jk_mhs_baa.setLayout(new java.awt.GridLayout(1, 0));

        grp_jk_mhs_baa.add(rd_laki_mhs);
        rd_laki_mhs.setText("Laki-laki");
        pnl_jk_mhs_baa.add(rd_laki_mhs);

        grp_jk_mhs_baa.add(rd_perempuan_mhs);
        rd_perempuan_mhs.setText("Perempuan");
        pnl_jk_mhs_baa.add(rd_perempuan_mhs);

        input_mhs.add(pnl_jk_mhs_baa);

        jLabel10.setText("Agama");
        input_mhs.add(jLabel10);

        cbx_Agama_mhs_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "> Islam", "> Kristen", "> Katholik", "> Hindu", "> Budha", "> Konghucu" }));
        input_mhs.add(cbx_Agama_mhs_baa);

        jLabel2_dsn1.setText("Tempat Tanggal Lahir");
        input_mhs.add(jLabel2_dsn1);
        input_mhs.add(txt_ttl_mhs_baa);

        jLabel11.setText("Alamat");
        input_mhs.add(jLabel11);
        input_mhs.add(txt_Alamat_mhs_baa);

        jLabel15.setText("Kota");
        input_mhs.add(jLabel15);

        cbx_kota_mhs_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== KOTA ===" }));
        input_mhs.add(cbx_kota_mhs_baa);

        jLabel21.setText("No Hp");
        input_mhs.add(jLabel21);
        input_mhs.add(txt_nohp_mhs_baa);

        jLabel8.setText("Status Masuk");
        input_mhs.add(jLabel8);

        cb_Status_mhs_baa.setText("Aktif");
        input_mhs.add(cb_Status_mhs_baa);

        javax.swing.GroupLayout border2Layout = new javax.swing.GroupLayout(border2);
        border2.setLayout(border2Layout);
        border2Layout.setHorizontalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        border2Layout.setVerticalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnadd_mhs_baa.setText("NEXT");
        btnadd_mhs_baa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_mhs_baaActionPerformed(evt);
            }
        });

        btn_clear_mhs_baa.setText("CLEAR");
        btn_clear_mhs_baa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_mhs_baaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_add_mhsLayout = new javax.swing.GroupLayout(panel_add_mhs);
        panel_add_mhs.setLayout(panel_add_mhsLayout);
        panel_add_mhsLayout.setHorizontalGroup(
            panel_add_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_mhsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_add_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(border2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_add_mhsLayout.createSequentialGroup()
                        .addGap(0, 324, Short.MAX_VALUE)
                        .addComponent(btn_clear_mhs_baa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnadd_mhs_baa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_add_mhsLayout.setVerticalGroup(
            panel_add_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_mhsLayout.createSequentialGroup()
                .addComponent(border2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_add_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd_mhs_baa)
                    .addComponent(btn_clear_mhs_baa))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        panelinduk_baa.add(panel_add_mhs, "cv_add_mhs");

        border1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Data Orang Tua Mahasiswa"));

        input_ortu.setLayout(new java.awt.GridLayout(7, 2, 0, 15));

        jLabel13.setText("Nama Ayah");
        input_ortu.add(jLabel13);
        input_ortu.add(txtnm_ayah_baa);

        jLabel14.setText("No KTP Ayah");
        input_ortu.add(jLabel14);
        input_ortu.add(txtktp_ayah_baa);

        jLabel16.setText("Nama Ibu");
        input_ortu.add(jLabel16);
        input_ortu.add(txtnm_ibu_baa);

        jLabel17.setText("No KTP Ibu");
        input_ortu.add(jLabel17);
        input_ortu.add(txtktp_ibu_baa);

        jLabel18.setText("Alamat Orang Tua");
        input_ortu.add(jLabel18);
        input_ortu.add(txt_alamatortu_baa);

        jLabel20.setText("Kota Orang Tua");
        input_ortu.add(jLabel20);

        cb_kota_ortu_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== KOTA ===" }));
        input_ortu.add(cb_kota_ortu_baa);

        jLabel19.setText("Telp Orang Tua");
        input_ortu.add(jLabel19);
        input_ortu.add(txt_telp_ortu_baa);

        javax.swing.GroupLayout border1Layout = new javax.swing.GroupLayout(border1);
        border1.setLayout(border1Layout);
        border1Layout.setHorizontalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_ortu, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        border1Layout.setVerticalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnadd_ortu_baa.setText("ADD");
        btnadd_ortu_baa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_ortu_baaActionPerformed(evt);
            }
        });

        btn_clear_ortu_baa.setText("CLEAR");
        btn_clear_ortu_baa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_ortu_baaActionPerformed(evt);
            }
        });

        btn_back_mhs.setText("BACK");
        btn_back_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_mhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_add_ortuLayout = new javax.swing.GroupLayout(panel_add_ortu);
        panel_add_ortu.setLayout(panel_add_ortuLayout);
        panel_add_ortuLayout.setHorizontalGroup(
            panel_add_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_add_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_add_ortuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btn_back_mhs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clear_ortu_baa)
                        .addGap(18, 18, 18)
                        .addComponent(btnadd_ortu_baa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(panel_add_ortuLayout.createSequentialGroup()
                        .addComponent(border1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panel_add_ortuLayout.setVerticalGroup(
            panel_add_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_add_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_add_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd_ortu_baa)
                    .addComponent(btn_clear_ortu_baa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_back_mhs))
                .addGap(187, 187, 187))
        );

        panelinduk_baa.add(panel_add_ortu, "cv_add_ortu_baa");

        TabelMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Periode", "Kode", "Nama Matkul", "Dosen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelMatkul);

        javax.swing.GroupLayout panel_matkulLayout = new javax.swing.GroupLayout(panel_matkul);
        panel_matkul.setLayout(panel_matkulLayout);
        panel_matkulLayout.setHorizontalGroup(
            panel_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matkulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_matkulLayout.setVerticalGroup(
            panel_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matkulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelinduk_baa.add(panel_matkul, "card5");

        border.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubah Data Dosen"));

        input_dsn.setLayout(new java.awt.GridLayout(11, 2, 0, 15));

        jLabel5_dsn.setText("NIP Dosen");
        input_dsn.add(jLabel5_dsn);

        cbx_nip_dsn_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelnipLayout = new javax.swing.GroupLayout(panelnip);
        panelnip.setLayout(panelnipLayout);
        panelnipLayout.setHorizontalGroup(
            panelnipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_NIP_dsn_baa)
            .addComponent(cbx_nip_dsn_baa, 0, 247, Short.MAX_VALUE)
        );
        panelnipLayout.setVerticalGroup(
            panelnipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnipLayout.createSequentialGroup()
                .addComponent(txt_NIP_dsn_baa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbx_nip_dsn_baa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        input_dsn.add(panelnip);

        jLabel12_dsn.setText("NIDN");
        input_dsn.add(jLabel12_dsn);
        input_dsn.add(txt_NIDN_dsn_baa);

        jLabel6_dsn.setText("Nama Dosen");
        input_dsn.add(jLabel6_dsn);
        input_dsn.add(txt_Nama_dsn_baa);

        jLabel11_dsn.setText("Alamat");
        input_dsn.add(jLabel11_dsn);
        input_dsn.add(txt_Alamat_dsn_baa);

        jLabel21_dsn.setText("Telepon");
        input_dsn.add(jLabel21_dsn);
        input_dsn.add(txt_nohp_dsn_baa);

        jLabel1_dsn.setText("Email");
        input_dsn.add(jLabel1_dsn);
        input_dsn.add(txt_email_dsn_baa);

        jLabel9_dsn.setText("Jenis Kelamin");
        input_dsn.add(jLabel9_dsn);

        pnl_jk_dsn.setLayout(new java.awt.GridLayout(1, 0));

        grp_jk_dsn_baa.add(rd_laki_dsn_baa);
        rd_laki_dsn_baa.setText("Laki-laki");
        pnl_jk_dsn.add(rd_laki_dsn_baa);

        grp_jk_dsn_baa.add(rd_perempuan_dsn_baa);
        rd_perempuan_dsn_baa.setText("Perempuan");
        pnl_jk_dsn.add(rd_perempuan_dsn_baa);

        input_dsn.add(pnl_jk_dsn);

        jLabel2_dsn.setText("TTL");
        input_dsn.add(jLabel2_dsn);
        input_dsn.add(txt_ttl_dsn_baa);

        jLabel8_dsn.setText("Status Kepegawaian");
        input_dsn.add(jLabel8_dsn);

        cb_Status_dsn_baa.setText("Aktif");
        input_dsn.add(cb_Status_dsn_baa);

        jLabel3_dsn.setText("Pendidikan tertinggi");
        input_dsn.add(jLabel3_dsn);

        cb_pendidikan_dsn_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== Pendidikan Tertinggi ===", "> S1", "> S2", "> S3" }));
        input_dsn.add(cb_pendidikan_dsn_baa);

        jLabel7_dsn.setText("Jabatan Akademik");
        input_dsn.add(jLabel7_dsn);

        cb_jbtn_dsn_baa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        input_dsn.add(cb_jbtn_dsn_baa);

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input_dsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(input_dsn, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_Ubah_dsn_baa.setText("Tambah Data");
        btn_Ubah_dsn_baa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ubah_dsn_baaActionPerformed(evt);
            }
        });

        btn_reset_dsn.setText("jButton1");

        javax.swing.GroupLayout panel_dsnLayout = new javax.swing.GroupLayout(panel_dsn);
        panel_dsn.setLayout(panel_dsnLayout);
        panel_dsnLayout.setHorizontalGroup(
            panel_dsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dsnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dsnLayout.createSequentialGroup()
                        .addComponent(border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dsnLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_reset_dsn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Ubah_dsn_baa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        panel_dsnLayout.setVerticalGroup(
            panel_dsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dsnLayout.createSequentialGroup()
                .addComponent(border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dsnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reset_dsn)
                    .addComponent(btn_Ubah_dsn_baa))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        panelinduk_baa.add(panel_dsn, "cv_add_dsn_baa");

        list_all_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRP", "Email", "Nama", "Prodi", "Jenis Kelamin", "Agama", "Alamat", "Kota", "No HP", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(list_all_mahasiswa);

        javax.swing.GroupLayout panel_mhs_tabelLayout = new javax.swing.GroupLayout(panel_mhs_tabel);
        panel_mhs_tabel.setLayout(panel_mhs_tabelLayout);
        panel_mhs_tabelLayout.setHorizontalGroup(
            panel_mhs_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(panel_mhs_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mhs_tabelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        panel_mhs_tabelLayout.setVerticalGroup(
            panel_mhs_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(panel_mhs_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_mhs_tabelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelinduk_baa.add(panel_mhs_tabel, "cv_list_mhs_baa");

        panel_dsn_tabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Dosen"));

        list_all_dsn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRP", "Email", "Nama", "Prodi", "Jenis Kelamin", "Agama", "Alamat", "Kota", "No HP", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(list_all_dsn);

        javax.swing.GroupLayout panel_dsn_tabelLayout = new javax.swing.GroupLayout(panel_dsn_tabel);
        panel_dsn_tabel.setLayout(panel_dsn_tabelLayout);
        panel_dsn_tabelLayout.setHorizontalGroup(
            panel_dsn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(panel_dsn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_dsn_tabelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_dsn_tabelLayout.setVerticalGroup(
            panel_dsn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(panel_dsn_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_dsn_tabelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelinduk_baa.add(panel_dsn_tabel, "cv_list_dsn_baa");

        menu_mhs.setText("Mahasiswa");

        add_data_mhs.setText("Tambah Data Mahasiswa");
        add_data_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_data_mhsActionPerformed(evt);
            }
        });
        menu_mhs.add(add_data_mhs);

        update_data_mhs.setText("Update Data Mahasiswa");
        update_data_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_data_mhsActionPerformed(evt);
            }
        });
        menu_mhs.add(update_data_mhs);

        list_data_mhs.setText("List Data Mahasiswa");
        list_data_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_data_mhsActionPerformed(evt);
            }
        });
        menu_mhs.add(list_data_mhs);

        jMenuBar1.add(menu_mhs);

        menu_dosen.setText("Dosen");

        add_data_dsn.setText("Tambah Data Dosen");
        add_data_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_data_dsnActionPerformed(evt);
            }
        });
        menu_dosen.add(add_data_dsn);

        update_data_dsn.setText("Ubah Data Dosen");
        update_data_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_data_dsnActionPerformed(evt);
            }
        });
        menu_dosen.add(update_data_dsn);

        list_data_dsn.setText("List Data Dosen");
        list_data_dsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_data_dsnActionPerformed(evt);
            }
        });
        menu_dosen.add(list_data_dsn);

        jMenuBar1.add(menu_dosen);

        menu_logout.setText("Logout");
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelinduk_baa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelinduk_baa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //untuk mengganti fungsi button add/update mahasiswa
    private void btn_Ubah_dsn_baaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ubah_dsn_baaActionPerformed
        //fungsi untuk menambah data
        if (btn_Ubah_dsn_baa.getText().equals("ADD")) {
            
        }
        //fungsiuntuk mengubah data
        else if (btn_Ubah_dsn_baa.getText().equals("UPDATE")) {
            cek_update_mhs();
        }
    }//GEN-LAST:event_btn_Ubah_dsn_baaActionPerformed

    private void btnadd_ortu_baaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_ortu_baaActionPerformed
        deklarasi_ortu();
        cek_ortu();
    }//GEN-LAST:event_btnadd_ortu_baaActionPerformed
    
    //untuk mengganti fungsi button add/update mahasiswa
    private void btnadd_mhs_baaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_mhs_baaActionPerformed
        //fungsi untuk menambah data
        if (btnadd_mhs_baa.getText().equals("NEXT")) {
            deklarasi_mhs();
            cek_mhs();
        }
        //fungsiuntuk mengubah data
        else if (btnadd_mhs_baa.getText().equals("UBAH DATA")) {
            cek_update_mhs();
        }
        
        
    }//GEN-LAST:event_btnadd_mhs_baaActionPerformed
    
    //untuk menampilkan halaman tambah data mahasiswa
    private void add_data_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_data_mhsActionPerformed
       clear_all();
       CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
       cl_baa.show(panelinduk_baa, "cv_add_mhs");
       title_baa.setText("Tambah Mahasiswa");
       txt_NRP_baa.setVisible(true);
       cb_NRP_baa.setVisible(false);
       btnadd_mhs_baa.setText("NEXT");
    }//GEN-LAST:event_add_data_mhsActionPerformed

    //untuk menampilkan halaman list data mahasiswa
    private void list_data_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_data_mhsActionPerformed
       CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
       cl_baa.show(panelinduk_baa, "cv_list_mhs_baa");
       title_baa.setText("Daftar Mahasiswa");
        
    }//GEN-LAST:event_list_data_mhsActionPerformed
    
    //untuk menampilkan halaman tambah data dosen
    private void add_data_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_data_dsnActionPerformed
        clear_all();
        cbx_nip_dsn_baa.setVisible(false);
        txt_NIP_dsn_baa.setVisible(true);
        CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
        cl_baa.show(panelinduk_baa, "cv_add_dsn_baa");
        title_baa.setText("Tambah data Dosen");
        btn_Ubah_dsn_baa.setText("ADD");
    }//GEN-LAST:event_add_data_dsnActionPerformed

    //untuk menampilkan halaman list data dosen
    private void list_data_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_data_dsnActionPerformed
       CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
       cl_baa.show(panelinduk_baa, "cv_list_dsn_baa");
       title_baa.setText("Daftar Dosen");
        
    }//GEN-LAST:event_list_data_dsnActionPerformed

    //untuk menampilkan halaman update data dosen
    private void update_data_dsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_data_dsnActionPerformed
        clear_all();
        cbx_nip_dsn_baa.setVisible(true);
        txt_NIP_dsn_baa.setVisible(false);
        CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
        cl_baa.show(panelinduk_baa, "cv_add_dsn_baa");
        title_baa.setText("Ubah data Dosen");
        btn_Ubah_dsn_baa.setText("UPDATE");
    }//GEN-LAST:event_update_data_dsnActionPerformed
    
    //untuk keluar ke halaman login
    private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
        new framelogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_logoutMouseClicked
    
    //untuk menampilkan halaman update data mahasiswa
    private void update_data_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_data_mhsActionPerformed
       clear_all();
       CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();cl_baa.show(panelinduk_baa, "cv_add_mhs");
       cb_NRP_baa.setVisible(true);
       txt_NRP_baa.setVisible(false);
       title_baa.setText("Ubah Mahasiswa");
       btnadd_mhs_baa.setText("UBAH DATA");
       tampil_nrp();
    }//GEN-LAST:event_update_data_mhsActionPerformed

    //untuk menghapus semua isi field mahasiswa
    private void btn_clear_mhs_baaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_mhs_baaActionPerformed
        clear_mhs();
    }//GEN-LAST:event_btn_clear_mhs_baaActionPerformed
    
    //untuk menghapus semua isi field ortu
    private void btn_clear_ortu_baaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_ortu_baaActionPerformed
       clear_ortu();
    }//GEN-LAST:event_btn_clear_ortu_baaActionPerformed
    
    //untuk menseting email secara otomatis
    private void txt_NRP_baaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_NRP_baaFocusLost
       deklarasi_mhs();
       if(nrp_mhs.equals("")){
           txt_Email_mhs_baa.setText("");
       }
       else{
          txt_Email_mhs_baa.setText(nrp_mhs+"@mhs.com"); 
       }
       
    }//GEN-LAST:event_txt_NRP_baaFocusLost
    
    //untuk kembali dari halaman ortu ke halaman mahasiswa
    private void btn_back_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_mhsActionPerformed
       CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
       cl_baa.show(panelinduk_baa, "cv_add_mhs");
       title_baa.setText("Tambah Mahasiswa");
       txt_NRP_baa.setVisible(true);
       cb_NRP_baa.setVisible(false);
       btnadd_mhs_baa.setText("NEXT");
    }//GEN-LAST:event_btn_back_mhsActionPerformed
    
    //untuk mengisi form detail mahasiswa secara otomatis
    private void cb_NRP_baaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_NRP_baaItemStateChanged
        if (cb_NRP_baa.getSelectedIndex()>0) {
            try{
                String get_fromnrp = "SELECT * FROM mahasiswa WHERE nrp='"+cb_NRP_baa.getSelectedItem()+"'";
                ResultSet res_fromnrp = con.prepareStatement(get_fromnrp).executeQuery();
                if(res_fromnrp.next()){
                    System.out.println(res_fromnrp.getString("Kota_Mahasiwa"));
                    txt_Nama_mhs_baa.setText(res_fromnrp.getString("nama_mahasiswa"));
                    txt_Email_mhs_baa.setText(res_fromnrp.getString("email"));
                    cbx_Prodi_baa.setSelectedItem("> "+res_fromnrp.getString("prodi"));
        
                    //untuk mengambil jenis kelamin
                    if(res_fromnrp.getString("Jenis_Kelamin").equals("Laki - Laki")){
                        rd_laki_mhs.setSelected(true);
                    }
                    else if(res_fromnrp.getString("Jenis_Kelamin").equals("Perempuan")){
                        rd_perempuan_mhs.setSelected(true);
                    }
                    
                    cbx_Agama_mhs_baa.setSelectedItem("> "+res_fromnrp.getString("agama"));
                    txt_ttl_mhs_baa.setText(res_fromnrp.getString("Tempat_Tanggal_Lahir_Mahasiswa"));
                    txt_Alamat_mhs_baa.setText(res_fromnrp.getString("alamat"));
                    cbx_kota_mhs_baa.setSelectedItem("> "+res_fromnrp.getString("Kota_Mahasiwa"));
                    txt_nohp_mhs_baa.setText(res_fromnrp.getString("no_hp"));
        
                    //untuk mengambil data status mahasiswa
                    if(res_fromnrp.getString("Status_Masuk").equals("Aktif")){
                        cb_Status_mhs_baa.setSelected(true);
                    }
                    else if(res_fromnrp.getString("Status_Masuk").equals("Tidak Aktif")){
                        cb_Status_mhs_baa.setSelected(false);
                    } 
                }  
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_cb_NRP_baaItemStateChanged
    
    //untuk menampilkan kota
    private void tampilkota(){
        try{
           String db_tmplkota = "SELECT * FROM kota ORDER BY Kota";
            PreparedStatement  ps_tmpl_kota = con.prepareStatement(db_tmplkota);
            ResultSet rs_tmplkota = ps_tmpl_kota.executeQuery();

            while(rs_tmplkota.next()){
                cbx_kota_mhs_baa.addItem("> "+rs_tmplkota.getString("Kota"));
                cb_kota_ortu_baa.addItem("> "+rs_tmplkota.getString("Kota"));
            } 
        }
        catch(Exception e){
            
        }
        
    }
    
// MAHASISWA
    
    //menghapus semua field
    private void clear_all(){
        clear_mhs();
        clear_ortu();
        clear_dsn();
    }
    
    //menghapus field mahasiswa
    private void clear_mhs(){
        cb_NRP_baa.setSelectedIndex(0);
        txt_NRP_baa.setText("");
        txt_Email_mhs_baa.setText("");
        txt_Nama_mhs_baa.setText("");
        cbx_Prodi_baa.setSelectedIndex(0);
        grp_jk_mhs_baa.clearSelection();
        cbx_Agama_mhs_baa.setSelectedIndex(0);
        txt_ttl_mhs_baa.setText("");
        txt_Alamat_mhs_baa.setText("");
        cbx_kota_mhs_baa.setSelectedIndex(0);
        txt_nohp_mhs_baa.setText("");
        cb_Status_mhs_baa.setSelected(false);
    }
    
    //deklarasi mahasiswa
    private void deklarasi_mhs(){
        indx_kota_mhs = cbx_kota_mhs_baa.getSelectedIndex();
        tampilkota();
        nrp_mhs = txt_NRP_baa.getText();
        email_mhs = txt_Email_mhs_baa.getText();
        nama_mhs = txt_Nama_mhs_baa.getText();
        prodi_mhs = hapus_tanda(cbx_Prodi_baa.getSelectedItem().toString());
        
        //untuk mengambil jenis kelamin
        if(rd_laki_mhs.isSelected()){
            jk_mhs = "Laki - Laki";
        }
        else if(rd_perempuan_mhs.isSelected()){
            jk_mhs = "Perempuan";
        }
        
        agama_mhs = hapus_tanda(cbx_Agama_mhs_baa.getSelectedItem().toString());
        ttl_mhs = txt_ttl_mhs_baa.getText();
        almt_mhs = txt_Alamat_mhs_baa.getText();
        kota_mhs = hapus_tanda(cbx_kota_mhs_baa.getItemAt(indx_kota_mhs));
        hp_mhs = txt_nohp_mhs_baa.getText();
                
        //untuk mengambil data status mahasiswa
        if(cb_Status_mhs_baa.isSelected() == true){
            stts_mhs = "Aktif";
        }
        else if(cb_Status_mhs_baa.isSelected() == false){
            stts_mhs = "Tidak Aktif";
        }
    }
    
    //untuk mengecek field mahasiswa, apakah ada field yang kosong
    private void cek_mhs(){
        try{
            String cek_nrp = "SELECT * FROM mahasiswa WHERE nrp='"+nrp_mhs+"'";
            ResultSet rs_cek_nrp = con.prepareStatement(cek_nrp).executeQuery();
            if(rs_cek_nrp.next()){
                JOptionPane.showMessageDialog(this, "Data dengan NRP "+nrp_mhs+" sudah ada");
            }
            else{
                String cek_email_mhs = "SELECT * FROM user WHERE Email='"+email_mhs+"'";
                ResultSet rs_cek_email_mhs = con.prepareStatement(cek_email_mhs).executeQuery();
                if(rs_cek_email_mhs.next()){
                 JOptionPane.showMessageDialog(this, "Data dengan Email "+email_mhs+" sudah ada");
                }
                else{
                    //jika ada field yang kosong
                    if(nrp_mhs.equals("") || email_mhs.equals("") || nama_mhs.equals("") || 
                        cbx_Prodi_baa.getSelectedIndex() == 0|| grp_jk_mhs_baa.getSelection() == null || 
                        cbx_Agama_mhs_baa.getSelectedIndex() == 0 || ttl_mhs.equals("") || almt_mhs.equals("") ||
                        cbx_kota_mhs_baa.getSelectedIndex() == 0  || hp_mhs.equals("") || !hp_mhs.matches("[0-9]*")){
                        
                        if(nrp_mhs.equals("") || email_mhs.equals("") || nama_mhs.equals("") || 
                                ttl_mhs.equals("") || almt_mhs.equals("") || hp_mhs.equals("")){
                                JOptionPane.showMessageDialog(this, "Mohon isi semua Field");
                        }
                        else if(grp_jk_mhs_baa.getSelection() == null){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih Jenis Kelamin Mahasiswa");       
                        }
                        else if(cbx_Prodi_baa.getSelectedIndex() == 0){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih prodi Mahasiswa");       
                        }
                        else if(cbx_Agama_mhs_baa.getSelectedIndex() == 0 ){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih Agama Mahasiswa");       
                        }
                        else if(cbx_kota_mhs_baa.getSelectedIndex() == 0 ){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih kota Mahasiswa");       
                        }
                        else if(!hp_mhs.matches("[0-9]*")){
                             JOptionPane.showMessageDialog(this, "Mohon isikan No HP hanya menggunakan angka");       
                        }
                    }
                            
                    //jika data belum terdaftar
                    else{
                        CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
                        cl_baa.show(panelinduk_baa, "cv_add_ortu_baa");
                        title_baa.setText("Tambah Mahasiswa");
                    }
                }
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
            
    }
    
    //untuk mendapatkan list nrp
    private void tampil_nrp(){
        try{
            String con_get_nrp = "SELECT * from mahasiswa";
            ResultSet res_get_nrp = con.prepareStatement(con_get_nrp).executeQuery();
            while(res_get_nrp.next()){
                cb_NRP_baa.addItem(res_get_nrp.getString("nrp"));
            }
        }
        catch(Exception e){
            
        }
    }
    
// ORANG TUA
    
    //menghapus field orang tua
    private void clear_ortu(){
        txtnm_ayah_baa.setText("");
        txtktp_ayah_baa.setText("");
        txtnm_ibu_baa.setText("");
        txtktp_ibu_baa.setText("");
        cb_kota_ortu_baa.setSelectedIndex(0);
        txt_telp_ortu_baa.setText("");
    }
    
    //deklarasi ortu
    private void deklarasi_ortu(){
        indx_kota_ortu_mhs = cb_kota_ortu_baa.getSelectedIndex();
        tampilkota();
        nama_ayah_mhs = txtnm_ayah_baa.getText();
        ktp_ayah_mhs = txtktp_ayah_baa.getText();
        nama_ibu_mhs = txtnm_ibu_baa.getText();
        ktp_ibu_mhs = txtktp_ibu_baa.getText();
        alamat_ortu_mhs = txt_alamatortu_baa.getText();
        kota_ortu_mhs = hapus_tanda(cb_kota_ortu_baa.getItemAt(indx_kota_ortu_mhs));
        hp_ortu_mhs= txt_telp_ortu_baa.getText();
    }
    
    //untuk mengecek field ortu, apakah ada field yang kosong
    private void cek_ortu(){
        //jika ada field yang kosong
        if(nama_ayah_mhs.equals("") || ktp_ayah_mhs.equals("") || nama_ibu_mhs.equals("") ||
                ktp_ibu_mhs.equals("") || alamat_ortu_mhs.equals("") || cb_kota_ortu_baa.getSelectedIndex() == 0  ||
                hp_ortu_mhs.equals("") || !hp_ortu_mhs.matches("[0-9]*")){
            JOptionPane.showMessageDialog(this, "Mohon cek Field Anda");
        }
        
        //jika tidak ada field yang kosong
        else{
            add_mhs();
        }
    }
    
    //untuk menambahkan data mahasiswa
    private void add_mhs(){
        try{
            System.out.println(jk_mhs);
            //untuk membuat user
            String add_user_mhs = "INSERT INTO user(Email,Password, Jenis_User) VALUES (?,?,?)";
            PreparedStatement ps_add_user_mhs = con.prepareStatement(add_user_mhs);
            ps_add_user_mhs.setString(1, email_mhs);
            ps_add_user_mhs.setString(2, "pass"+nrp_mhs);
            ps_add_user_mhs.setString(3, "Mahasiswa");
            ps_add_user_mhs.executeUpdate();
            
            //untuk menyimpan data mahasiswa
            String add_mhs = "INSERT INTO mahasiswa(nrp, nama_mahasiswa, prodi, Status_Masuk, "
            + "Jenis_Kelamin, Agama, alamat, Tempat_Tanggal_Lahir_Mahasiswa, Kota_Mahasiwa, "
            + "email, no_hp, Nama_Ayah, Nomor_KTP_Ayah, Nama_Ibu, Nomor_KTP_Ibu, Telepon_Orang_Tua, "
            + "Alamat_Orang_Tua, Kota_Orang_Tua) VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
            PreparedStatement ps_add_mhs = con.prepareStatement(add_mhs);
            ps_add_mhs.setString(1, nrp_mhs);
            ps_add_mhs.setString(2, nama_mhs);
            ps_add_mhs.setString(3, prodi_mhs);
            ps_add_mhs.setString(4, stts_mhs);
            ps_add_mhs.setString(5, jk_mhs);
            ps_add_mhs.setString(6, agama_mhs);
            ps_add_mhs.setString(7, almt_mhs);
            ps_add_mhs.setString(8, ttl_mhs);
            ps_add_mhs.setString(9, kota_mhs);
            ps_add_mhs.setString(10, email_mhs);
            ps_add_mhs.setString(11, hp_mhs);
            ps_add_mhs.setString(12, nama_ayah_mhs);
            ps_add_mhs.setString(13, ktp_ayah_mhs);
            ps_add_mhs.setString(14, nama_ibu_mhs);
            ps_add_mhs.setString(15, ktp_ibu_mhs);
            ps_add_mhs.setString(16, hp_ortu_mhs);
            ps_add_mhs.setString(17, alamat_ortu_mhs);
            ps_add_mhs.setString(18, kota_ortu_mhs);
            ps_add_mhs.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Data dengan NRP "+nrp_mhs+" sudah ditambahkan");
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    //cek field pada update mahasiswa
    private void cek_update_mhs(){
        if(cb_NRP_baa.getSelectedIndex() == 0 ||nama_mhs.equals("") || grp_jk_mhs_baa.getSelection() == null || 
            cbx_Agama_mhs_baa.getSelectedIndex() == 0 || ttl_mhs.equals("") || almt_mhs.equals("") ||
            cbx_kota_mhs_baa.getSelectedIndex() == 0  || hp_mhs.equals("") || !hp_mhs.matches("[0-9]*")){
                        
            if(nama_mhs.equals("") || ttl_mhs.equals("") || almt_mhs.equals("") || hp_mhs.equals("")){
                JOptionPane.showMessageDialog(this, "Mohon isi semua Field");
            }
            else if(cb_NRP_baa.getSelectedIndex() == 0){
               JOptionPane.showMessageDialog(this, "Mohon Pilih Data Mahasiswa yang akan diubah");   
            }
            else if(grp_jk_mhs_baa.getSelection() == null){
                JOptionPane.showMessageDialog(this, "Mohon Pilih Jenis Kelamin Mahasiswa");       
            }
            else if(cbx_Agama_mhs_baa.getSelectedIndex() == 0 ){
                JOptionPane.showMessageDialog(this, "Mohon Pilih Agama Mahasiswa");       
            }
            else if(cbx_kota_mhs_baa.getSelectedIndex() == 0 ){
                JOptionPane.showMessageDialog(this, "Mohon Pilih kota Mahasiswa");       
            }
            else if(!hp_mhs.matches("[0-9]*")){
                JOptionPane.showMessageDialog(this, "Mohon isikan No HP hanya menggunakan angka");       
            }
        }
        else{
            update_mhs();
        }
    }
    
    //untuk mengganti data mahasiswa
    private void update_mhs(){
        deklarasi_mhs();
        try{
            String db_update_mhs = "UPDATE mahasiswa SET nama_mahasiswa = ? ,"
                    + "Jenis_Kelamin = ? ,Agama = ? ,Tempat_Tanggal_Lahir_Mahasiswa = ? ,"
                    + "alamat = ? ,Kota_Mahasiwa = ? ,no_hp = ? ,Status_Masuk = ? "
                    + "WHERE nrp='"+cb_NRP_baa.getSelectedItem()+"'";
            PreparedStatement ps_up_mhs = con.prepareStatement(db_update_mhs);
            ps_up_mhs.setString(1, nama_mhs);
            ps_up_mhs.setString(2, jk_mhs);
            ps_up_mhs.setString(3, agama_mhs);
            ps_up_mhs.setString(4, ttl_mhs);
            ps_up_mhs.setString(5, almt_mhs);
            ps_up_mhs.setString(6, kota_mhs);
            ps_up_mhs.setString(7, hp_mhs);
            ps_up_mhs.setString(8, stts_mhs);
            ps_up_mhs.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data pada NRP "+cb_NRP_baa.getSelectedItem()+"telah berhasil diubah");
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }
    
//DOSEN
    //menghapus field dosen
    private void clear_dsn(){
        cbx_nip_dsn_baa.setSelectedIndex(0);
        txt_NIP_dsn_baa.setText("");
        txt_NIDN_dsn_baa.setText("");
        txt_Nama_dsn_baa.setText("");
        txt_Alamat_dsn_baa.setText("");
        txt_nohp_dsn_baa.setText("");
        txt_email_dsn_baa.setText("");
        txt_ttl_dsn_baa.setText("");
        cb_Status_dsn_baa.setSelected(false);
        cb_pendidikan_dsn_baa.setSelectedIndex(0);
        cb_jbtn_dsn_baa.setSelectedIndex(0);
    }
    
    //deklarasi dosen
    private void deklarasi_dsn(){
        indx_kota_mhs = cbx_kota_mhs_baa.getSelectedIndex();
        tampilkota();
        nrp_mhs = txt_NRP_baa.getText();
        email_mhs = txt_Email_mhs_baa.getText();
        nama_mhs = txt_Nama_mhs_baa.getText();
        prodi_mhs = hapus_tanda(cbx_Prodi_baa.getSelectedItem().toString());
        
        //untuk mengambil jenis kelamin
        if(rd_laki_mhs.isSelected()){
            jk_mhs = "Laki - Laki";
        }
        else if(rd_perempuan_mhs.isSelected()){
            jk_mhs = "Perempuan";
        }
        
        agama_mhs = hapus_tanda(cbx_Agama_mhs_baa.getSelectedItem().toString());
        ttl_mhs = txt_ttl_mhs_baa.getText();
        almt_mhs = txt_Alamat_mhs_baa.getText();
        kota_mhs = hapus_tanda(cbx_kota_mhs_baa.getItemAt(indx_kota_mhs));
        hp_mhs = txt_nohp_mhs_baa.getText();
                
        //untuk mengambil data status mahasiswa
        if(cb_Status_mhs_baa.isSelected() == true){
            stts_mhs = "Aktif";
        }
        else if(cb_Status_mhs_baa.isSelected() == false){
            stts_mhs = "Tidak Aktif";
        }
    }
    
    //untuk mengecek field dosen, apakah ada field yang kosong
    private void cek_dsn(){
        try{
            String cek_nrp = "SELECT * FROM mahasiswa WHERE nrp='"+nrp_mhs+"'";
            ResultSet rs_cek_nrp = con.prepareStatement(cek_nrp).executeQuery();
            if(rs_cek_nrp.next()){
                JOptionPane.showMessageDialog(this, "Data dengan NRP "+nrp_mhs+" sudah ada");
            }
            else{
                String cek_email_mhs = "SELECT * FROM user WHERE Email='"+email_mhs+"'";
                ResultSet rs_cek_email_mhs = con.prepareStatement(cek_email_mhs).executeQuery();
                if(rs_cek_email_mhs.next()){
                 JOptionPane.showMessageDialog(this, "Data dengan Email "+email_mhs+" sudah ada");
                }
                else{
                    //jika ada field yang kosong
                    if(nrp_mhs.equals("") || email_mhs.equals("") || nama_mhs.equals("") || 
                        cbx_Prodi_baa.getSelectedIndex() == 0|| grp_jk_mhs_baa.getSelection() == null || 
                        cbx_Agama_mhs_baa.getSelectedIndex() == 0 || ttl_mhs.equals("") || almt_mhs.equals("") ||
                        cbx_kota_mhs_baa.getSelectedIndex() == 0  || hp_mhs.equals("") || !hp_mhs.matches("[0-9]*")){
                        
                        if(nrp_mhs.equals("") || email_mhs.equals("") || nama_mhs.equals("") || 
                                ttl_mhs.equals("") || almt_mhs.equals("") || hp_mhs.equals("")){
                                JOptionPane.showMessageDialog(this, "Mohon isi semua Field");
                        }
                        else if(grp_jk_mhs_baa.getSelection() == null){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih Jenis Kelamin Mahasiswa");       
                        }
                        else if(cbx_Prodi_baa.getSelectedIndex() == 0){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih prodi Mahasiswa");       
                        }
                        else if(cbx_Agama_mhs_baa.getSelectedIndex() == 0 ){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih Agama Mahasiswa");       
                        }
                        else if(cbx_kota_mhs_baa.getSelectedIndex() == 0 ){
                             JOptionPane.showMessageDialog(this, "Mohon Pilih kota Mahasiswa");       
                        }
                        else if(!hp_mhs.matches("[0-9]*")){
                             JOptionPane.showMessageDialog(this, "Mohon isikan No HP hanya menggunakan angka");       
                        }
                    }
                            
                    //jika data belum terdaftar
                    else{
                        CardLayout cl_baa = (CardLayout) panelinduk_baa.getLayout();
                        cl_baa.show(panelinduk_baa, "cv_add_ortu_baa");
                        title_baa.setText("Tambah Mahasiswa");
                    }
                }
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
            
    }
    
    //untuk menghapus tanda ">"
    private String hapus_tanda(String str){
        return str.substring(2);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framebaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framebaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framebaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framebaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framebaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelMatkul;
    private javax.swing.JMenuItem add_data_dsn;
    private javax.swing.JMenuItem add_data_mhs;
    private javax.swing.JPanel border;
    private javax.swing.JPanel border1;
    private javax.swing.JPanel border2;
    private javax.swing.JButton btn_Ubah_dsn_baa;
    private javax.swing.JButton btn_back_mhs;
    private javax.swing.JButton btn_clear_mhs_baa;
    private javax.swing.JButton btn_clear_ortu_baa;
    private javax.swing.JButton btn_reset_dsn;
    private javax.swing.JButton btnadd_mhs_baa;
    private javax.swing.JButton btnadd_ortu_baa;
    private javax.swing.JComboBox<String> cb_NRP_baa;
    private javax.swing.JCheckBox cb_Status_dsn_baa;
    private javax.swing.JCheckBox cb_Status_mhs_baa;
    private javax.swing.JComboBox<String> cb_jbtn_dsn_baa;
    private javax.swing.JComboBox<String> cb_kota_ortu_baa;
    private javax.swing.JComboBox<String> cb_pendidikan_dsn_baa;
    private javax.swing.JComboBox<String> cbx_Agama_mhs_baa;
    private javax.swing.JComboBox<String> cbx_Prodi_baa;
    private javax.swing.JComboBox<String> cbx_kota_mhs_baa;
    private javax.swing.JComboBox<String> cbx_nip_dsn_baa;
    private javax.swing.ButtonGroup grp_jk_dsn_baa;
    private javax.swing.ButtonGroup grp_jk_mhs_baa;
    private javax.swing.JPanel input_dsn;
    private javax.swing.JPanel input_mhs;
    private javax.swing.JPanel input_ortu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_dsn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel12_dsn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1_dsn;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel21_dsn;
    private javax.swing.JLabel jLabel2_dsn;
    private javax.swing.JLabel jLabel2_dsn1;
    private javax.swing.JLabel jLabel3_dsn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_dsn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_dsn;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7_dsn;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8_dsn;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_dsn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable list_all_dsn;
    private javax.swing.JTable list_all_mahasiswa;
    private javax.swing.JMenuItem list_data_dsn;
    private javax.swing.JMenuItem list_data_mhs;
    private javax.swing.JMenu menu_dosen;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JMenu menu_mhs;
    private javax.swing.JPanel panel_add_mhs;
    private javax.swing.JPanel panel_add_ortu;
    private javax.swing.JPanel panel_dsn;
    private javax.swing.JPanel panel_dsn_tabel;
    private javax.swing.JPanel panel_matkul;
    private javax.swing.JPanel panel_mhs_tabel;
    private javax.swing.JPanel panel_nrp;
    private javax.swing.JPanel panelinduk_baa;
    private javax.swing.JPanel panelnip;
    private javax.swing.JPanel pnl_jk_dsn;
    private javax.swing.JPanel pnl_jk_mhs_baa;
    private javax.swing.JRadioButton rd_laki_dsn_baa;
    private javax.swing.JRadioButton rd_laki_mhs;
    private javax.swing.JRadioButton rd_perempuan_dsn_baa;
    private javax.swing.JRadioButton rd_perempuan_mhs;
    private javax.swing.JLabel title_baa;
    private javax.swing.JTextField txt_Alamat_dsn_baa;
    private javax.swing.JTextField txt_Alamat_mhs_baa;
    private javax.swing.JTextField txt_Email_mhs_baa;
    private javax.swing.JTextField txt_NIDN_dsn_baa;
    private javax.swing.JTextField txt_NIP_dsn_baa;
    private javax.swing.JTextField txt_NRP_baa;
    private javax.swing.JTextField txt_Nama_dsn_baa;
    private javax.swing.JTextField txt_Nama_mhs_baa;
    private javax.swing.JTextField txt_alamatortu_baa;
    private javax.swing.JTextField txt_email_dsn_baa;
    private javax.swing.JTextField txt_nohp_dsn_baa;
    private javax.swing.JTextField txt_nohp_mhs_baa;
    private javax.swing.JTextField txt_telp_ortu_baa;
    private javax.swing.JTextField txt_ttl_dsn_baa;
    private javax.swing.JTextField txt_ttl_mhs_baa;
    private javax.swing.JTextField txtktp_ayah_baa;
    private javax.swing.JTextField txtktp_ibu_baa;
    private javax.swing.JTextField txtnm_ayah_baa;
    private javax.swing.JTextField txtnm_ibu_baa;
    private javax.swing.JMenuItem update_data_dsn;
    private javax.swing.JMenuItem update_data_mhs;
    // End of variables declaration//GEN-END:variables
}
