/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_akhir;

import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import static tugas_akhir.framedosen.con;

/**
 *
 * @author ACER
 */
public class framemahasiswa extends javax.swing.JFrame {

    public static Connection con = new koneksi().ambil_koneksi();

    private static framelogin email_lgn = new framelogin();
    private static String kota_ortu_mhs;
    String image_path = null;
    FileInputStream fis = null;
    private static String Nama_Lengkap, NRP, Program_Studi, Status_Masuk, Agama, Alamat,  Jenis_Kelamin, Kota, TTL, No_Hp,
            Nama_Ayah, KTP_Ayah, Nama_Ibu, KTP_Ibu, Telepon_Ortu, Alamat_Ortu, Kota_Ortu, prodi;

    /**
     * Creates new form framemahasiswa
     */
    public framemahasiswa() {
        initComponents();
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_pribadi");
        header_mhs.setText("PROFILE MAHASISWA");
        tampilkota();
        tampil_data();
        tampil_data_ortu();
        tampilfotomahasiswa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ls_jk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        header_mhs = new javax.swing.JLabel();
        panelinduk_mhs = new javax.swing.JPanel();
        panel_mhs = new javax.swing.JPanel();
        border = new javax.swing.JPanel();
        input_mhs = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_NRP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Email_mhs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Nama_mhs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pnl_jk_mhs = new javax.swing.JPanel();
        rd_laki_mhs = new javax.swing.JRadioButton();
        rd_perempuan_mhs = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbx_Agama_mhs = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_Alamat_mhs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbx_kota_mhs = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txt_nohp_mhs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        labelfoto = new javax.swing.JLabel();
        btnUbah_mhs = new javax.swing.JButton();
        panel_ortu = new javax.swing.JPanel();
        border1 = new javax.swing.JPanel();
        input_ortu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtnm_ayah = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtktp_ayah = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnm_ibu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtktp_ibu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_alamatortu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cb_kota_ortu = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txt_telp_ortu = new javax.swing.JTextField();
        btnUbah_ortu = new javax.swing.JButton();
        panel_matkul = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelMatkul_mhs = new javax.swing.JTable();
        panel_tmpl_pribadi = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_tmpl_nama_mhs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_tmpl_nrp_mhs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_tmpl_prodi_mhs = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_tmpl_stts_msuk_mhs = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_tmpl_agama_mhs = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_tmpl_jk_mhs = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_tmpl_ttl_mhs = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_tmpl_no_mhs = new javax.swing.JLabel();
        panel_tmpl_ortu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lbl_tmpl_nm_ayah_mhs = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbl_tmpl_ktp_ayah_mhs = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_tmpl_nm_ibu_mhs = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbl_tmpl_ktp_ibu_mhs = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl_tmpl_telp_ortu_mhs = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl_tmpl_almt_ortu_mhs = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbl_tmpl_kota_ortu_mhs = new javax.swing.JLabel();
        panel_ubh_pass_mhs = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnl_ubh_dsn = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        get_up_email_dsn = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        get_up_nip_dsn = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        get_up_nama_dsn = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_ubh_asli_mhs = new javax.swing.JPasswordField();
        jLabel37 = new javax.swing.JLabel();
        txt_ubh_pass_mhs = new javax.swing.JPasswordField();
        jLabel38 = new javax.swing.JLabel();
        txt_ubh_repass_mhs = new javax.swing.JPasswordField();
        cb_up_password_mhs = new javax.swing.JCheckBox();
        btn_up_mhs = new javax.swing.JButton();
        panel_wisuda = new javax.swing.JPanel();
        border2 = new javax.swing.JPanel();
        input_mhs_wisuda = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        txt_Nama_mhs2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txt_judul_ta = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txt_dsn_pembimbing = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        btnFoto_wsd = new javax.swing.JButton();
        labelfoto1 = new javax.swing.JLabel();
        btnajukan_mhs = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_beranda_mhs = new javax.swing.JMenu();
        sm_tmpl_pribadi = new javax.swing.JMenuItem();
        sm_tmpl_ortu = new javax.swing.JMenuItem();
        sm_ubh_pass_mhs = new javax.swing.JMenuItem();
        menu_ubah_mhs = new javax.swing.JMenu();
        sm_pribadi = new javax.swing.JMenuItem();
        sm_ortu = new javax.swing.JMenuItem();
        menu_akademik_mhs = new javax.swing.JMenu();
        menu_tampil_jadwal = new javax.swing.JMenuItem();
        menu_wisuda = new javax.swing.JMenu();
        menu_daftar_wisuda = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        header_mhs.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        header_mhs.setText("SAKTI");
        jPanel1.add(header_mhs, new java.awt.GridBagConstraints());

        panelinduk_mhs.setLayout(new java.awt.CardLayout());

        border.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        jLabel5.setText("NRP");

        txt_NRP.setEditable(false);
        txt_NRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_NRPMouseClicked(evt);
            }
        });

        jLabel12.setText("Email");

        txt_Email_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_Email_mhsMouseClicked(evt);
            }
        });

        jLabel6.setText("Nama");

        txt_Nama_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nama_mhsActionPerformed(evt);
            }
        });

        jLabel9.setText("Jenis Kelamin");

        pnl_jk_mhs.setLayout(new java.awt.GridLayout(1, 0));

        ls_jk.add(rd_laki_mhs);
        rd_laki_mhs.setText("Laki-laki");
        pnl_jk_mhs.add(rd_laki_mhs);

        ls_jk.add(rd_perempuan_mhs);
        rd_perempuan_mhs.setText("Perempuan");
        pnl_jk_mhs.add(rd_perempuan_mhs);

        jLabel10.setText("Agama");

        cbx_Agama_mhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "Islam", "Kristen", "Katholik", "Hindu", "Budha", "Konghucu" }));

        jLabel11.setText("Alamat");

        txt_Alamat_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Alamat_mhsActionPerformed(evt);
            }
        });

        jLabel15.setText("Kota");

        cbx_kota_mhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== PILIH ===" }));

        jLabel21.setText("No Hp");

        txt_nohp_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohp_mhsActionPerformed(evt);
            }
        });
        txt_nohp_mhs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nohp_mhsKeyTyped(evt);
            }
        });

        jLabel7.setText("Upload Foto");

        btnFoto.setText("Pilih Foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        labelfoto.setText("*sumber foto");

        javax.swing.GroupLayout input_mhsLayout = new javax.swing.GroupLayout(input_mhs);
        input_mhs.setLayout(input_mhsLayout);
        input_mhsLayout.setHorizontalGroup(
            input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_mhsLayout.createSequentialGroup()
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NRP))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Email_mhs))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Nama_mhs))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_Agama_mhs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_jk_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Alamat_mhs))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_kota_mhs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nohp_mhs))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addComponent(labelfoto)
                        .addGap(0, 393, Short.MAX_VALUE)))
                .addContainerGap())
        );
        input_mhsLayout.setVerticalGroup(
            input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_mhsLayout.createSequentialGroup()
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NRP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Email_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nama_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_jk_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_Agama_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Alamat_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_kota_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nohp_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(input_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(input_mhsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7))
                    .addComponent(btnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(labelfoto)
                .addContainerGap())
        );

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnUbah_mhs.setText("Ubah Data");
        btnUbah_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah_mhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_mhsLayout = new javax.swing.GroupLayout(panel_mhs);
        panel_mhs.setLayout(panel_mhsLayout);
        panel_mhsLayout.setHorizontalGroup(
            panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mhsLayout.createSequentialGroup()
                .addContainerGap(384, Short.MAX_VALUE)
                .addComponent(btnUbah_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(panel_mhsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_mhsLayout.setVerticalGroup(
            panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mhsLayout.createSequentialGroup()
                .addComponent(border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUbah_mhs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_mhs, "cv_pribadi");

        border1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Orang Tua Mahasiswa"));

        input_ortu.setLayout(new java.awt.GridLayout(7, 2, 0, 15));

        jLabel13.setText("Nama Ayah");
        input_ortu.add(jLabel13);

        txtnm_ayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnm_ayahActionPerformed(evt);
            }
        });
        input_ortu.add(txtnm_ayah);

        jLabel14.setText("No KTP Ayah");
        input_ortu.add(jLabel14);

        txtktp_ayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtktp_ayahActionPerformed(evt);
            }
        });
        input_ortu.add(txtktp_ayah);

        jLabel16.setText("Nama Ibu");
        input_ortu.add(jLabel16);

        txtnm_ibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnm_ibuActionPerformed(evt);
            }
        });
        input_ortu.add(txtnm_ibu);

        jLabel17.setText("No KTP Ibu");
        input_ortu.add(jLabel17);

        txtktp_ibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtktp_ibuActionPerformed(evt);
            }
        });
        input_ortu.add(txtktp_ibu);

        jLabel18.setText("Alamat Orang Tua");
        input_ortu.add(jLabel18);

        txt_alamatortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatortuActionPerformed(evt);
            }
        });
        input_ortu.add(txt_alamatortu);

        jLabel20.setText("Kota Orang Tua");
        input_ortu.add(jLabel20);

        cb_kota_ortu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== KOTA ===" }));
        input_ortu.add(cb_kota_ortu);

        jLabel19.setText("Telp Orang Tua");
        input_ortu.add(jLabel19);

        txt_telp_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telp_ortuActionPerformed(evt);
            }
        });
        input_ortu.add(txt_telp_ortu);

        javax.swing.GroupLayout border1Layout = new javax.swing.GroupLayout(border1);
        border1.setLayout(border1Layout);
        border1Layout.setHorizontalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_ortu, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        border1Layout.setVerticalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnUbah_ortu.setText("Ubah Data");
        btnUbah_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah_ortuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ortuLayout = new javax.swing.GroupLayout(panel_ortu);
        panel_ortu.setLayout(panel_ortuLayout);
        panel_ortuLayout.setHorizontalGroup(
            panel_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ortuLayout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addComponent(btnUbah_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panel_ortuLayout.setVerticalGroup(
            panel_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUbah_ortu)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_ortu, "cv_ortu");

        TabelMatkul_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Periode", "Tanggal", "Waktu", "Ruang", "Nama Matkul", "Nama Dosen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelMatkul_mhs);

        javax.swing.GroupLayout panel_matkulLayout = new javax.swing.GroupLayout(panel_matkul);
        panel_matkul.setLayout(panel_matkulLayout);
        panel_matkulLayout.setHorizontalGroup(
            panel_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matkulLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_matkulLayout.setVerticalGroup(
            panel_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matkulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelinduk_mhs.add(panel_matkul, "cv_matkul");

        panel_tmpl_pribadi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Data Pribadi Mahasiswa")));

        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );

        jPanel5.add(jDesktopPane1);

        jPanel3.setLayout(new java.awt.GridLayout(8, 2, 0, 15));

        jLabel1.setText("Nama Lengkap");
        jPanel3.add(jLabel1);

        lbl_tmpl_nama_mhs.setText("Nama Lengkap");
        jPanel3.add(lbl_tmpl_nama_mhs);

        jLabel3.setText("NRP");
        jPanel3.add(jLabel3);

        lbl_tmpl_nrp_mhs.setText("NRP");
        jPanel3.add(lbl_tmpl_nrp_mhs);

        jLabel2.setText("Program Studi");
        jPanel3.add(jLabel2);

        lbl_tmpl_prodi_mhs.setText("Program Studi");
        jPanel3.add(lbl_tmpl_prodi_mhs);

        jLabel4.setText("Status Masuk");
        jPanel3.add(jLabel4);

        lbl_tmpl_stts_msuk_mhs.setText("Status Masuk");
        jPanel3.add(lbl_tmpl_stts_msuk_mhs);

        jLabel22.setText("Agama");
        jPanel3.add(jLabel22);

        lbl_tmpl_agama_mhs.setText("Agama");
        jPanel3.add(lbl_tmpl_agama_mhs);

        jLabel23.setText("Jenis Kelamin");
        jPanel3.add(jLabel23);

        lbl_tmpl_jk_mhs.setText("Jenis Kelamin");
        jPanel3.add(lbl_tmpl_jk_mhs);

        jLabel24.setText("Tempat / Tanggal Lahir");
        jPanel3.add(jLabel24);

        lbl_tmpl_ttl_mhs.setText("Tempat / Tanggal Lahir");
        jPanel3.add(lbl_tmpl_ttl_mhs);

        jLabel25.setText("No Hp");
        jPanel3.add(jLabel25);

        lbl_tmpl_no_mhs.setText("No Hp");
        jPanel3.add(lbl_tmpl_no_mhs);

        javax.swing.GroupLayout panel_tmpl_pribadiLayout = new javax.swing.GroupLayout(panel_tmpl_pribadi);
        panel_tmpl_pribadi.setLayout(panel_tmpl_pribadiLayout);
        panel_tmpl_pribadiLayout.setHorizontalGroup(
            panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_pribadiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tmpl_pribadiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_tmpl_pribadiLayout.setVerticalGroup(
            panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tmpl_pribadiLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_tmpl_pribadiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );

        panelinduk_mhs.add(panel_tmpl_pribadi, "cv_tmpl_pribadi");

        panel_tmpl_ortu.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Orang Tua Mahasiswa"));

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 0, 15));

        jLabel28.setText("Nama Ayah");
        jPanel2.add(jLabel28);

        lbl_tmpl_nm_ayah_mhs.setText("Nama Ayah");
        jPanel2.add(lbl_tmpl_nm_ayah_mhs);

        jLabel26.setText("Nomor KTP Ayah");
        jPanel2.add(jLabel26);

        lbl_tmpl_ktp_ayah_mhs.setText("Nomor KTP Ayah");
        jPanel2.add(lbl_tmpl_ktp_ayah_mhs);

        jLabel27.setText("Nama Ibu\t");
        jPanel2.add(jLabel27);

        lbl_tmpl_nm_ibu_mhs.setText("Nama Ibu\t");
        jPanel2.add(lbl_tmpl_nm_ibu_mhs);

        jLabel29.setText("Nomor KTP Ibu");
        jPanel2.add(jLabel29);

        lbl_tmpl_ktp_ibu_mhs.setText("Nomor KTP Ibu");
        jPanel2.add(lbl_tmpl_ktp_ibu_mhs);

        jLabel30.setText("Telepon Orang Tua");
        jPanel2.add(jLabel30);

        lbl_tmpl_telp_ortu_mhs.setText("Telepon Orang Tua");
        jPanel2.add(lbl_tmpl_telp_ortu_mhs);

        jLabel31.setText("Alamat Orang Tua");
        jPanel2.add(jLabel31);

        lbl_tmpl_almt_ortu_mhs.setText("Alamat Orang Tua");
        jPanel2.add(lbl_tmpl_almt_ortu_mhs);

        jLabel32.setText("Kota Orang Tua");
        jPanel2.add(jLabel32);

        lbl_tmpl_kota_ortu_mhs.setText("Kota Orang Tua");
        jPanel2.add(lbl_tmpl_kota_ortu_mhs);

        javax.swing.GroupLayout panel_tmpl_ortuLayout = new javax.swing.GroupLayout(panel_tmpl_ortu);
        panel_tmpl_ortu.setLayout(panel_tmpl_ortuLayout);
        panel_tmpl_ortuLayout.setHorizontalGroup(
            panel_tmpl_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_tmpl_ortuLayout.setVerticalGroup(
            panel_tmpl_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_tmpl_ortu, "cv_tmpl_ortu");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubah Password"));

        pnl_ubh_dsn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_ubh_dsn.setLayout(new java.awt.GridLayout(6, 2, 0, 15));

        jLabel33.setText("Email");
        pnl_ubh_dsn.add(jLabel33);

        get_up_email_dsn.setText("email mahasiswa");
        pnl_ubh_dsn.add(get_up_email_dsn);

        jLabel34.setText("NRP");
        pnl_ubh_dsn.add(jLabel34);

        get_up_nip_dsn.setText("NRP mahasiswa");
        pnl_ubh_dsn.add(get_up_nip_dsn);

        jLabel35.setText("Nama");
        pnl_ubh_dsn.add(jLabel35);

        get_up_nama_dsn.setText("nama mahasiswa");
        pnl_ubh_dsn.add(get_up_nama_dsn);

        jLabel36.setText("Password Sekarang");
        pnl_ubh_dsn.add(jLabel36);
        pnl_ubh_dsn.add(txt_ubh_asli_mhs);

        jLabel37.setText("Password Baru");
        pnl_ubh_dsn.add(jLabel37);

        txt_ubh_pass_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ubh_pass_mhsActionPerformed(evt);
            }
        });
        pnl_ubh_dsn.add(txt_ubh_pass_mhs);

        jLabel38.setText("Ulangi password");
        pnl_ubh_dsn.add(jLabel38);
        pnl_ubh_dsn.add(txt_ubh_repass_mhs);

        cb_up_password_mhs.setText("Tampil Password");
        cb_up_password_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_up_password_mhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_up_password_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_ubh_dsn, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(cb_up_password_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_ubh_dsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );

        btn_up_mhs.setText("Ubah Password");
        btn_up_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_up_mhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ubh_pass_mhsLayout = new javax.swing.GroupLayout(panel_ubh_pass_mhs);
        panel_ubh_pass_mhs.setLayout(panel_ubh_pass_mhsLayout);
        panel_ubh_pass_mhsLayout.setHorizontalGroup(
            panel_ubh_pass_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ubh_pass_mhsLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(btn_up_mhs)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ubh_pass_mhsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_ubh_pass_mhsLayout.setVerticalGroup(
            panel_ubh_pass_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ubh_pass_mhsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_up_mhs)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_ubh_pass_mhs, "cv_tmpl_ubh_pass_mhs");

        border2.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Wisuda"));

        jLabel45.setText("Nilai IPK");

        txt_Nama_mhs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nama_mhs2ActionPerformed(evt);
            }
        });

        jLabel44.setText("Judul Tugas Akhir");

        txt_judul_ta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_judul_taActionPerformed(evt);
            }
        });

        jLabel46.setText("Dosen Pembimbing");

        txt_dsn_pembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dsn_pembimbingActionPerformed(evt);
            }
        });
        txt_dsn_pembimbing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dsn_pembimbingKeyTyped(evt);
            }
        });

        jLabel47.setText("Upload Bukti Pembayaran");

        btnFoto_wsd.setText("Pilih Foto");
        btnFoto_wsd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFoto_wsdActionPerformed(evt);
            }
        });

        labelfoto1.setText("*sumber foto");

        javax.swing.GroupLayout input_mhs_wisudaLayout = new javax.swing.GroupLayout(input_mhs_wisuda);
        input_mhs_wisuda.setLayout(input_mhs_wisudaLayout);
        input_mhs_wisudaLayout.setHorizontalGroup(
            input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_judul_ta))
            .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_dsn_pembimbing))
            .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFoto_wsd, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelfoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))))
            .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Nama_mhs2))
        );
        input_mhs_wisudaLayout.setVerticalGroup(
            input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nama_mhs2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_judul_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_dsn_pembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(input_mhs_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(input_mhs_wisudaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel47))
                    .addComponent(btnFoto_wsd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelfoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout border2Layout = new javax.swing.GroupLayout(border2);
        border2.setLayout(border2Layout);
        border2Layout.setHorizontalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs_wisuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        border2Layout.setVerticalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
            .addGroup(border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs_wisuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnajukan_mhs.setText("AJUKAN");
        btnajukan_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajukan_mhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_wisudaLayout = new javax.swing.GroupLayout(panel_wisuda);
        panel_wisuda.setLayout(panel_wisudaLayout);
        panel_wisudaLayout.setHorizontalGroup(
            panel_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_wisudaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_wisudaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnajukan_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panel_wisudaLayout.setVerticalGroup(
            panel_wisudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_wisudaLayout.createSequentialGroup()
                .addComponent(border2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnajukan_mhs)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_wisuda, "cv_wisuda_mhs");

        menu_beranda_mhs.setText("Profile");

        sm_tmpl_pribadi.setText("Tampil Data Pribadi");
        sm_tmpl_pribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_tmpl_pribadiActionPerformed(evt);
            }
        });
        menu_beranda_mhs.add(sm_tmpl_pribadi);

        sm_tmpl_ortu.setText("Tampil Data Orang Tua");
        sm_tmpl_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_tmpl_ortuActionPerformed(evt);
            }
        });
        menu_beranda_mhs.add(sm_tmpl_ortu);

        sm_ubh_pass_mhs.setText("Ubah Password");
        sm_ubh_pass_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_ubh_pass_mhsActionPerformed(evt);
            }
        });
        menu_beranda_mhs.add(sm_ubh_pass_mhs);

        jMenuBar1.add(menu_beranda_mhs);

        menu_ubah_mhs.setText("Ubah Data");

        sm_pribadi.setText("Data Pribadi");
        sm_pribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_pribadiActionPerformed(evt);
            }
        });
        menu_ubah_mhs.add(sm_pribadi);

        sm_ortu.setText("Orang Tua");
        sm_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_ortuActionPerformed(evt);
            }
        });
        menu_ubah_mhs.add(sm_ortu);

        jMenuBar1.add(menu_ubah_mhs);

        menu_akademik_mhs.setText("Akademik");

        menu_tampil_jadwal.setText("Jadwal");
        menu_tampil_jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tampil_jadwalActionPerformed(evt);
            }
        });
        menu_akademik_mhs.add(menu_tampil_jadwal);

        jMenuBar1.add(menu_akademik_mhs);

        menu_wisuda.setText("Wisuda");

        menu_daftar_wisuda.setText("Daftar Wisuda");
        menu_daftar_wisuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_daftar_wisudaActionPerformed(evt);
            }
        });
        menu_wisuda.add(menu_daftar_wisuda);

        jMenuBar1.add(menu_wisuda);

        menu_logout.setText("Logout");
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelinduk_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelinduk_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Alamat_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Alamat_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Alamat_mhsActionPerformed

    private void txt_Nama_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nama_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nama_mhsActionPerformed

    private void txtnm_ayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnm_ayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnm_ayahActionPerformed

    private void txtktp_ayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtktp_ayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtktp_ayahActionPerformed

    private void txtnm_ibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnm_ibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnm_ibuActionPerformed

    private void txtktp_ibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtktp_ibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtktp_ibuActionPerformed

    private void txt_alamatortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatortuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatortuActionPerformed

    private void txt_telp_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telp_ortuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telp_ortuActionPerformed

    private void txt_nohp_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohp_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohp_mhsActionPerformed

    //untuk pindah ke halaman ubah data ortu
    private void sm_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_ortuActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_ortu");
        header_mhs.setText("UBAH DATA ORANG TUA");
    }//GEN-LAST:event_sm_ortuActionPerformed

    //untuk pindah ke halaman ubah data pribadi
    private void sm_pribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_pribadiActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_pribadi");
        header_mhs.setText("UBAH DATA PRIBADI");
    }//GEN-LAST:event_sm_pribadiActionPerformed

    private void btnUbah_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah_mhsActionPerformed
        // TODO add your handling code here:
        String ls_nrp = txt_NRP.getText();
        String ls_email = txt_Email_mhs.getText();
        String ls_nama = txt_Nama_mhs.getText();
        String ls_jk = "";
        if (rd_laki_mhs.isSelected()) {
            ls_jk = rd_laki_mhs.getText();
        } else if (rd_perempuan_mhs.isSelected()) {
            ls_jk = rd_perempuan_mhs.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Jenis Kelamin belum dipilh");
            return;
        }
        
        String ls_agama = cbx_Agama_mhs.getSelectedItem().toString();
        if (cbx_Agama_mhs.getSelectedItem().toString().equals("===PILIH===")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih Agama Mahasiswa!");
            return;
        }
        
        String ls_alamat = txt_Alamat_mhs.getText();
        String ls_kota = cbx_kota_mhs.getSelectedItem().toString();
        if (cbx_kota_mhs.getSelectedItem().toString().equals("=== PILIH ===")) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih kota asal mahasiswa!");
            return;
        }
        String ls_hp = txt_nohp_mhs.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Statement state = con.createStatement();
            int result = state.executeUpdate("UPDATE mahasiswa SET nama_mahasiswa = '" + ls_nama + "', Jenis_Kelamin = '" + ls_jk + "', Agama = '"+ls_agama+"', alamat = '" + ls_alamat
                    + "', Kota_Mahasiswa = '" + hapus_tanda(ls_kota) + "', no_hp = '" + ls_hp + "' where nrp = '" + ls_nrp + "'");
            JOptionPane.showMessageDialog(this, "Data Mahasiswa Anda Berhasil Diubah!");
            try { //error
                InputStream image = new FileInputStream(new File(image_path));
                int res = state.executeUpdate("UPDATE mahasiswa SET foto = ? where nrp = '" + ls_nrp + "'");
                System.out.println(ls_nrp);
                JOptionPane.showMessageDialog(this, "Foto telah terupdate");

            } catch (Exception e) {
                System.out.println("Foto gak kenek sek an!");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_btnUbah_mhsActionPerformed

    private void btnUbah_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah_ortuActionPerformed
        // TODO add your handling code here:
        String ls_1 = txtnm_ayah.getText();
        String ls_2 = txtktp_ayah.getText();
        String ls_3 = txtnm_ibu.getText();
        String ls_4 = txtktp_ibu.getText();
        String ls_5 = txt_alamatortu.getText();
        String ls_6 = cb_kota_ortu.getSelectedItem().toString();
        String ls_7 = txt_telp_ortu.getText();
        
        if (cb_kota_ortu.getSelectedItem().toString().equals("=== KOTA ===")){
            JOptionPane.showMessageDialog(this, "Silahkan pilih kota!");
            return;
        }
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Statement state = con.createStatement();
            int result = state.executeUpdate(" Update mahasiswa SET Nama_Ayah = '"+ls_1+"', Nomor_KTP_Ayah = '"+ls_2+"', Nama_Ibu = '"+ls_3+"', "
                    + "Nomor_KTP_Ibu = '"+ls_4+"', Alamat_Orang_Tua = '"+ls_5+"', Kota_Orang_Tua = '"+hapus_tanda(ls_6)+"', Telepon_Orang_Tua = '"+ls_7+"' "
                            + "where nrp = '"+NRP+"'");
            JOptionPane.showMessageDialog(this, "Data Orang Tua telah terubah");
        } catch (Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btnUbah_ortuActionPerformed

    private void sm_tmpl_pribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_tmpl_pribadiActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_pribadi");
        header_mhs.setText("PROFILE MAHASISWA");
    }//GEN-LAST:event_sm_tmpl_pribadiActionPerformed

    private void sm_tmpl_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_tmpl_ortuActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_ortu");
        header_mhs.setText("PROFILE ORANG TUA");
    }//GEN-LAST:event_sm_tmpl_ortuActionPerformed

    private void menu_tampil_jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tampil_jadwalActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_matkul");
        header_mhs.setText("JADWAL");
        prodi = "";
        
        
        if(Program_Studi.equals("DKV")){
            prodi = "DKV";
        }
        else if(Program_Studi.equals("Teknik Informatika")){
            prodi = "TI";
        }
        else if(Program_Studi.equals("Sistem Informasi")){
            prodi = "SI";
        }
        else if(Program_Studi.equals("Manajemen Informasi")){
            prodi = "MI";
        }
        try{
            DefaultTableModel dftjdwl = (DefaultTableModel) TabelMatkul_mhs.getModel();
            dftjdwl.setRowCount(0); 
            String dbdftjdwl = "select mk.Periode periode,\n" +
                                "cast(k.waktu AS DATE) tanggal,\n" +
                                "cast(k.waktu AS TIME) waktu,\n" +
                                "k.ruang ruang, mk.nama_mata_kuliah matkul,dsn.nama_dosen nm_dosen\n" +
                                "FROM jadwal j\n" +
                                "INNER JOIN mata_kuliah mk ON mk.kode_mata_kuliah = j.kode_mata_kuliah\n" +
                                "INNER JOIN kelas k ON k.id_kelas = j.id_kelas\n" +
                                "INNER JOIN dosen dsn ON dsn.nip_dosen = j.nip_dosen \n"+
                                "WHERE j.prodi LIKE '"+prodi+"' ;";
            ResultSet res_dftjdwl = con.prepareStatement(dbdftjdwl).executeQuery();
            
            while(res_dftjdwl.next()){
                Object data[] = new Object[6];
                data[0] = res_dftjdwl.getString("periode");
                data[1] = res_dftjdwl.getString("tanggal");
                data[2] = res_dftjdwl.getString("waktu");
                data[3] = res_dftjdwl.getString("ruang");
                data[4] = res_dftjdwl.getString("matkul");
                data[5] = res_dftjdwl.getString("nm_dosen");
                
                dftjdwl.addRow(data);
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_menu_tampil_jadwalActionPerformed

    private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
        new framelogin().setVisible(true);
        dispose();
        lbl_tmpl_nama_mhs.setText("");
        lbl_tmpl_nrp_mhs.setText("");
        lbl_tmpl_prodi_mhs.setText("");
        lbl_tmpl_stts_msuk_mhs.setText("");
        lbl_tmpl_agama_mhs.setText("");
        lbl_tmpl_jk_mhs.setText("");
        lbl_tmpl_ttl_mhs.setText("");
        lbl_tmpl_no_mhs.setText("");

        txtnm_ayah.setText("");
        txtktp_ayah.setText("");
        txtnm_ibu.setText("");
        txtktp_ibu.setText("");
        txt_alamatortu.setText("");
        cb_kota_ortu.setSelectedIndex(0);
        txt_telp_ortu.setText("");

    }//GEN-LAST:event_menu_logoutMouseClicked

    private void txt_nohp_mhsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nohp_mhsKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nohp_mhsKeyTyped

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        // TODO add your handling code here:
        String path = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));

        //extensi file
        FileNameExtensionFilter extension = new FileNameExtensionFilter("*Image", "*.jpg", "*.png", "*.jpeg");
        chooser.addChoosableFileFilter(extension);

        int filestate = chooser.showSaveDialog(null);

        File selectedImage = chooser.getSelectedFile();
        String filename = selectedImage.getName();
        //Ambil nama file foto

        if (filename.endsWith(".jpg") || filename.endsWith(".JPG") || filename.endsWith(".PNG") || filename.endsWith(".png") || filename.endsWith(".jpeg")) {
            if (filestate == JFileChooser.APPROVE_OPTION) {
                path = selectedImage.getAbsolutePath();
                labelfoto.setText(path); //set lokasi direktor file yang diambil
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_DEFAULT));
                jLabel8.setIcon(imageIcon);

                FileInputStream fis = null;
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    fis = new FileInputStream(path);

                    String updatefoto = "UPDATE mahasiswa SET foto = ? WHERE Email = '" + email_lgn.email + "'";
                    PreparedStatement ps_updatefoto = con.prepareStatement(updatefoto);
                    ps_updatefoto.setBinaryStream(1, fis);
                    int response = JOptionPane.showConfirmDialog(this, "Apakah foto sudah sesuai?", "Konfirmasi!", JOptionPane.YES_NO_OPTION);
                    if (response == 0) {
                        int record = ps_updatefoto.executeUpdate();
                        if (record == 1) {
                            JOptionPane.showMessageDialog(this, "Foto berhasil diunggah!", "Selesai", 1);
                        } else {
                            JOptionPane.showMessageDialog(this, "Maaf.. ", "foto gagal diunggah!", 1);
                        }
                    }
                    if (response == 1) {
                        JOptionPane.showMessageDialog(this, "Dibatalkan oleh user!", "Batal", 1);
                        labelfoto.setText("*sumber foto");
                    }
                } catch (Exception e) {
                    System.out.println("" + e);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih foto dibatalkan user");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hanya foto yang bisa diupload!");
            return;
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void txt_NRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_NRPMouseClicked
        // TODO add your handling code here:
        txt_NRP.setEditable(false);
    }//GEN-LAST:event_txt_NRPMouseClicked

    private void txt_Email_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_Email_mhsMouseClicked
        // TODO add your handling code here:
        txt_Email_mhs.setEditable(false);
    }//GEN-LAST:event_txt_Email_mhsMouseClicked

    private void sm_ubh_pass_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_ubh_pass_mhsActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_ubh_pass_mhs");

        get_data();
        header_mhs.setText("UBAH PASSWORD");

        get_up_email_dsn.setText(email_lgn.email);
        get_up_nip_dsn.setText(NRP);
        get_up_nama_dsn.setText(Nama_Lengkap);
    }//GEN-LAST:event_sm_ubh_pass_mhsActionPerformed

    private void txt_ubh_pass_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ubh_pass_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ubh_pass_mhsActionPerformed

    private void cb_up_password_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_up_password_mhsActionPerformed
        if(cb_up_password_mhs.isSelected()){
            txt_ubh_asli_mhs.setEchoChar((char)0);
            txt_ubh_pass_mhs.setEchoChar((char)0);
            txt_ubh_repass_mhs.setEchoChar((char)0);
        }
        else{
            txt_ubh_asli_mhs.setEchoChar('*');
            txt_ubh_pass_mhs.setEchoChar('*');
            txt_ubh_repass_mhs.setEchoChar('*');
        }
    }//GEN-LAST:event_cb_up_password_mhsActionPerformed

    private void btn_up_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_up_mhsActionPerformed
        get_data();
        String up_dsn_asli = txt_ubh_asli_mhs.getText();
        String up_dsn_baru1 = txt_ubh_pass_mhs.getText();
        String up_dsn_baru2 = txt_ubh_repass_mhs.getText();

        if(up_dsn_asli.equals("") || up_dsn_baru1.equals("") || up_dsn_baru2.equals("")){
            JOptionPane.showMessageDialog(this, "Mohon isi Semua kolom");
        }

        else  if(up_dsn_baru1.length() < 8 || up_dsn_baru2.length() < 8 ){
            JOptionPane.showMessageDialog(this,"Password minimal 8 karakter");
        }

        else if(!up_dsn_baru1.equals(up_dsn_baru2)){
            JOptionPane.showMessageDialog(this, "Password tidak sama");
        }

        else{
            try{
                String up_get_pass = "SELECT Password FROM user WHERE Email='"+email_lgn.email+"'";
                ResultSet res_get_pass = con.prepareStatement(up_get_pass).executeQuery();
                if(res_get_pass.next()){
                    String up_get_pass_asli = res_get_pass.getString("Password");
                    if(up_dsn_asli.equals(up_get_pass_asli)){
                        String update_up_pass = "UPDATE user SET Password = ? WHERE Email='"+email_lgn.email+"'";
                        PreparedStatement ps_up_pass = con.prepareStatement(update_up_pass);
                        ps_up_pass.setString(1, up_dsn_baru1);
                        ps_up_pass.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Password Sudah terubah silahkan login ulang");
                        new framelogin().setVisible(true);
                        dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Mohon Cek Kembali password anda");
                    }

                }

            }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
        }

    }//GEN-LAST:event_btn_up_mhsActionPerformed

    private void txt_judul_taActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_judul_taActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_judul_taActionPerformed

    private void txt_dsn_pembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dsn_pembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dsn_pembimbingActionPerformed

    private void txt_dsn_pembimbingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dsn_pembimbingKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dsn_pembimbingKeyTyped

    private void btnFoto_wsdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoto_wsdActionPerformed
        // TODO add your handling code here:
        String path = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));

        //extensi file
        FileNameExtensionFilter extension = new FileNameExtensionFilter("*Image", "*.jpg", "*.png", "*.jpeg");
        chooser.addChoosableFileFilter(extension);

        int filestate = chooser.showSaveDialog(null);

        File selectedImage = chooser.getSelectedFile();
        String filename = selectedImage.getName();
        //Ambil nama file foto

        if (filename.endsWith(".jpg") || filename.endsWith(".JPG") || filename.endsWith(".PNG") || filename.endsWith(".png") || filename.endsWith(".jpeg")) {
            if (filestate == JFileChooser.APPROVE_OPTION) {
                path = selectedImage.getAbsolutePath();
                labelfoto1.setText(path); //set lokasi direktor file yang diambil
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_DEFAULT));
                jLabel8.setIcon(imageIcon);

                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    fis = new FileInputStream(path);

                    String updatefoto = "UPDATE wisuda SET foto = ? WHERE Email = '" + email_lgn.email + "'";
                    PreparedStatement ps_updatefoto = con.prepareStatement(updatefoto);
                    ps_updatefoto.setBinaryStream(1, fis);
                    int response = JOptionPane.showConfirmDialog(this, "Apakah foto sudah sesuai?", "Konfirmasi!", JOptionPane.YES_NO_OPTION);
                    if (response == 0) {
                        int record = ps_updatefoto.executeUpdate();
                        if (record == 1) {
                            JOptionPane.showMessageDialog(this, "Foto berhasil diunggah!", "Selesai", 1);
                        } else {
                            JOptionPane.showMessageDialog(this, "Maaf.. ", "foto gagal diunggah!", 1);
                        }
                    }
                    if (response == 1) {
                        JOptionPane.showMessageDialog(this, "Dibatalkan oleh user!", "Batal", 1);
                        labelfoto1.setText("*sumber foto");
                    }
                } catch (Exception e) {
                    System.out.println("" + e);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Pilih foto dibatalkan user");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Hanya foto yang bisa diupload!");
            return;
        }
    }//GEN-LAST:event_btnFoto_wsdActionPerformed

    private void txt_Nama_mhs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nama_mhs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nama_mhs2ActionPerformed
    
    //untuk mendaftar wisuda
    private void menu_daftar_wisudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_daftar_wisudaActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_wisuda_mhs");
        header_mhs.setText("DAFTAR WISUDA");
    }//GEN-LAST:event_menu_daftar_wisudaActionPerformed

    private void btnajukan_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajukan_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnajukan_mhsActionPerformed

    //untuk menampilkan kota
    private void tampilkota() {
        cb_kota_ortu.removeAllItems();
        cbx_kota_mhs.removeAllItems();
        cb_kota_ortu.addItem("=== KOTA ===");
        cbx_kota_mhs.addItem("=== KOTA ===");

        try {
            String db_tmplkota_ortu = "SELECT * FROM kota";
            PreparedStatement ps_tmpl_kota = con.prepareStatement(db_tmplkota_ortu);
            ResultSet rs_tmplkota_ortu = ps_tmpl_kota.executeQuery();

            while (rs_tmplkota_ortu.next()) {
                cb_kota_ortu.addItem(">  " + rs_tmplkota_ortu.getString("Kota"));
                cbx_kota_mhs.addItem(">  " + rs_tmplkota_ortu.getString("Kota"));

                kota_ortu_mhs = hapus_tanda(cb_kota_ortu.getSelectedItem().toString());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    private void get_data() {
        try {
            String sqltampil = "select * from mahasiswa WHERE email='" + email_lgn.email + "'";
            PreparedStatement ps_tampil = con.prepareStatement(sqltampil);
            ResultSet res_tampil = ps_tampil.executeQuery();

            if (res_tampil.next()) {
                Nama_Lengkap = res_tampil.getString("nama_mahasiswa");
                NRP = res_tampil.getString("nrp");
                Program_Studi = res_tampil.getString("prodi");
                Status_Masuk = res_tampil.getString("Status_Masuk");
                Agama = res_tampil.getString("Agama");
                Alamat = res_tampil.getString("alamat");
                Jenis_Kelamin = res_tampil.getString("Jenis_Kelamin");
                TTL = res_tampil.getString("Tempat_Tanggal_Lahir_Mahasiswa");
                Kota = res_tampil.getString("Kota_Mahasiswa");
                No_Hp = res_tampil.getString("no_hp");
                Nama_Ayah = res_tampil.getString("Nama_Ayah");
                KTP_Ayah = res_tampil.getString("Nomor_KTP_Ayah");
                Nama_Ibu = res_tampil.getString("Nama_Ibu");
                KTP_Ibu = res_tampil.getString("Nomor_KTP_Ibu");
                Telepon_Ortu = res_tampil.getString("Telepon_Orang_Tua");
                Alamat_Ortu = res_tampil.getString("Alamat_Orang_Tua");
                Kota_Ortu = res_tampil.getString("Kota_Orang_Tua");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void tampil_data() {
        get_data();
        lbl_tmpl_nama_mhs.setText(Nama_Lengkap);
        txt_Nama_mhs.setText(Nama_Lengkap);
        
        
        lbl_tmpl_nrp_mhs.setText(NRP);
        txt_NRP.setText(NRP);
        
        txt_Email_mhs.setText(email_lgn.email);
        
        lbl_tmpl_prodi_mhs.setText(Program_Studi);
        
        
        lbl_tmpl_stts_msuk_mhs.setText(Status_Masuk);
        
        
        lbl_tmpl_agama_mhs.setText(Agama);
        cbx_Agama_mhs.setSelectedItem(Agama);
        
        txt_Alamat_mhs.setText(Alamat);
        
        
        lbl_tmpl_jk_mhs.setText(Jenis_Kelamin);
        if(Jenis_Kelamin != null){
            if (Jenis_Kelamin.equals("Laki-laki") || Jenis_Kelamin.equals("Laki-Laki") || Jenis_Kelamin.equals("laki-laki")){
            rd_laki_mhs.setSelected(true);
            } else if (Jenis_Kelamin.equals("Perempuan") || Jenis_Kelamin.equals("perempuan") ){
                rd_perempuan_mhs.setSelected(true);
            }
        }
        
        lbl_tmpl_ttl_mhs.setText(TTL);
        if(Kota != null){
          cbx_kota_mhs.setSelectedItem(">  " +Kota);  
        }
        
        lbl_tmpl_no_mhs.setText(No_Hp);
        txt_nohp_mhs.setText(No_Hp);
        
        ImageIcon img_file_profil = new ImageIcon("./src/folderimg/profilmhs/prfl_"+NRP+".png");
        Image img_scale_profil = img_file_profil.getImage();
        ImageIcon img_profilmhs = new ImageIcon(img_scale_profil.getScaledInstance(163, 159,  java.awt.Image.SCALE_SMOOTH));
        jLabel8.setIcon(img_profilmhs);
        
        
    }

    private void tampil_data_ortu() {
        get_data();
        txtnm_ayah.setText(Nama_Ayah);
        lbl_tmpl_nm_ayah_mhs.setText(Nama_Ayah);
        
        txtktp_ayah.setText(KTP_Ayah);
        lbl_tmpl_ktp_ayah_mhs.setText(KTP_Ayah);
        
        txtnm_ibu.setText(Nama_Ibu);
        lbl_tmpl_nm_ibu_mhs.setText(Nama_Ibu);
        
        txtktp_ibu.setText(KTP_Ibu);
        lbl_tmpl_ktp_ibu_mhs.setText(KTP_Ibu);
        
        txt_alamatortu.setText(Alamat_Ortu);
        lbl_tmpl_almt_ortu_mhs.setText(Alamat_Ortu);
        
        cb_kota_ortu.setSelectedItem(">  "+Kota_Ortu);
        lbl_tmpl_kota_ortu_mhs.setText(Kota_Ortu);
        
        txt_telp_ortu.setText(Telepon_Ortu);
        lbl_tmpl_telp_ortu_mhs.setText(Telepon_Ortu);
    }
    
     private void tampilfotomahasiswa() {
        get_data();
        InputStream input;
        FileOutputStream output;
        try {
            PreparedStatement pst = con.prepareStatement("SELECT foto FROM mahasiswa WHERE Email = '" + email_lgn.email + "'");
            ResultSet rs = pst.executeQuery();
            File theFile = new File("fotomahasiswa.png");
            output = new FileOutputStream(theFile);

            if (rs.next()) {
                input = rs.getBinaryStream("bukti_pembayaran");
                byte buffer[] = new byte[1024];
                while (input.read(buffer) > 0) {
                    output.write(buffer);
                }
                String path = theFile.getAbsolutePath();
                ImageIcon myImage = new ImageIcon(path);
                Image img = myImage.getImage();

//                 ImageIcon imageIcon = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_DEFAULT));
//                    jLabel8.setIcon(imageIcon);
                Image newImage = img.getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon image = new ImageIcon(newImage);
                jLabel8.setIcon(image);
            }
        } catch (Exception e) {
            System.out.println(""+e);
        }
    }

    //untuk menghapus tanda ">"
    private String hapus_tanda(String str) {
        return str.substring(2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framemahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelMatkul_mhs;
    private javax.swing.JPanel border;
    private javax.swing.JPanel border1;
    private javax.swing.JPanel border2;
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnFoto_wsd;
    private javax.swing.JButton btnUbah_mhs;
    private javax.swing.JButton btnUbah_ortu;
    private javax.swing.JButton btn_up_mhs;
    private javax.swing.JButton btnajukan_mhs;
    private javax.swing.JComboBox<String> cb_kota_ortu;
    private javax.swing.JCheckBox cb_up_password_mhs;
    private javax.swing.JComboBox<String> cbx_Agama_mhs;
    private javax.swing.JComboBox<String> cbx_kota_mhs;
    private javax.swing.JLabel get_up_email_dsn;
    private javax.swing.JLabel get_up_nama_dsn;
    private javax.swing.JLabel get_up_nip_dsn;
    private javax.swing.JLabel header_mhs;
    private javax.swing.JPanel input_mhs;
    private javax.swing.JPanel input_mhs_wisuda;
    private javax.swing.JPanel input_ortu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelfoto;
    private javax.swing.JLabel labelfoto1;
    private javax.swing.JLabel lbl_tmpl_agama_mhs;
    private javax.swing.JLabel lbl_tmpl_almt_ortu_mhs;
    private javax.swing.JLabel lbl_tmpl_jk_mhs;
    private javax.swing.JLabel lbl_tmpl_kota_ortu_mhs;
    private javax.swing.JLabel lbl_tmpl_ktp_ayah_mhs;
    private javax.swing.JLabel lbl_tmpl_ktp_ibu_mhs;
    private javax.swing.JLabel lbl_tmpl_nama_mhs;
    private javax.swing.JLabel lbl_tmpl_nm_ayah_mhs;
    private javax.swing.JLabel lbl_tmpl_nm_ibu_mhs;
    private javax.swing.JLabel lbl_tmpl_no_mhs;
    private javax.swing.JLabel lbl_tmpl_nrp_mhs;
    private javax.swing.JLabel lbl_tmpl_prodi_mhs;
    private javax.swing.JLabel lbl_tmpl_stts_msuk_mhs;
    private javax.swing.JLabel lbl_tmpl_telp_ortu_mhs;
    private javax.swing.JLabel lbl_tmpl_ttl_mhs;
    private javax.swing.ButtonGroup ls_jk;
    private javax.swing.JMenu menu_akademik_mhs;
    private javax.swing.JMenu menu_beranda_mhs;
    private javax.swing.JMenuItem menu_daftar_wisuda;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JMenuItem menu_tampil_jadwal;
    private javax.swing.JMenu menu_ubah_mhs;
    private javax.swing.JMenu menu_wisuda;
    private javax.swing.JPanel panel_matkul;
    private javax.swing.JPanel panel_mhs;
    private javax.swing.JPanel panel_ortu;
    private javax.swing.JPanel panel_tmpl_ortu;
    private javax.swing.JPanel panel_tmpl_pribadi;
    private javax.swing.JPanel panel_ubh_pass_mhs;
    private javax.swing.JPanel panel_wisuda;
    private javax.swing.JPanel panelinduk_mhs;
    private javax.swing.JPanel pnl_jk_mhs;
    private javax.swing.JPanel pnl_ubh_dsn;
    private javax.swing.JRadioButton rd_laki_mhs;
    private javax.swing.JRadioButton rd_perempuan_mhs;
    private javax.swing.JMenuItem sm_ortu;
    private javax.swing.JMenuItem sm_pribadi;
    private javax.swing.JMenuItem sm_tmpl_ortu;
    private javax.swing.JMenuItem sm_tmpl_pribadi;
    private javax.swing.JMenuItem sm_ubh_pass_mhs;
    private javax.swing.JTextField txt_Alamat_mhs;
    private javax.swing.JTextField txt_Email_mhs;
    private javax.swing.JTextField txt_NRP;
    private javax.swing.JTextField txt_Nama_mhs;
    private javax.swing.JTextField txt_Nama_mhs2;
    private javax.swing.JTextField txt_alamatortu;
    private javax.swing.JTextField txt_dsn_pembimbing;
    private javax.swing.JTextField txt_judul_ta;
    private javax.swing.JTextField txt_nohp_mhs;
    private javax.swing.JTextField txt_telp_ortu;
    private javax.swing.JPasswordField txt_ubh_asli_mhs;
    private javax.swing.JPasswordField txt_ubh_pass_mhs;
    private javax.swing.JPasswordField txt_ubh_repass_mhs;
    private javax.swing.JTextField txtktp_ayah;
    private javax.swing.JTextField txtktp_ibu;
    private javax.swing.JTextField txtnm_ayah;
    private javax.swing.JTextField txtnm_ibu;
    // End of variables declaration//GEN-END:variables
}
