/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_akhir;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author ACER
 */
public class framemahasiswa extends javax.swing.JFrame {
    public static Connection con = new koneksi().ambil_koneksi();
    private static String kota_ortu_mhs;
    /**
     * Creates new form framemahasiswa
     */
    public framemahasiswa() {
        initComponents();
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_pribadi");
        header_mhs.setText("PROFILE MAHASISWA");
        tampilkota();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ls_jk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        header_mhs = new javax.swing.JLabel();
        panelinduk_mhs = new javax.swing.JPanel();
        panel_mhs = new javax.swing.JPanel();
        border = new javax.swing.JPanel();
        input_mhs = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_NRP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_Email_mhs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Nama_mhs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pnl_jk_mhs = new javax.swing.JPanel();
        rd_laki_mhs = new javax.swing.JRadioButton();
        rd_perempuan_mhs = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbx_Agama_mhs = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_Alamat_mhs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbx_kota_mhs = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        txt_nohp_mhs = new javax.swing.JTextField();
        btnUbah_mhs = new javax.swing.JButton();
        panel_ortu = new javax.swing.JPanel();
        border1 = new javax.swing.JPanel();
        input_ortu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtnm_ayah = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtktp_ayah = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnm_ibu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtktp_ibu = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_alamatortu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cb_kota_ortu = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txt_telp_ortu = new javax.swing.JTextField();
        btnUbah_ortu = new javax.swing.JButton();
        panel_matkul = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelMatkul_mhs = new javax.swing.JTable();
        panel_tmpl_pribadi = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_tmpl_nama_mhs = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_tmpl_nrp_mhs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_tmpl_prodi_mhs = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_tmpl_stts_msuk_mhs = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_tmpl_agama_mhs = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_tmpl_jk_mhs = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_tmpl_ttl_mhs = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_tmpl_no_mhs = new javax.swing.JLabel();
        panel_tmpl_ortu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lbl_tmpl_nm_ayah_mhs = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbl_tmpl_ktp_ayah_mhs = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbl_tmpl_nm_ibu_mhs = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbl_tmpl_ktp_ibu_mhs = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbl_tmpl_telp_ortu_mhs = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl_tmpl_almt_ortu_mhs = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lbl_tmpl_kota_ortu_mhs = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_beranda_mhs = new javax.swing.JMenu();
        sm_tmpl_pribadi = new javax.swing.JMenuItem();
        sm_tmpl_ortu = new javax.swing.JMenuItem();
        menu_ubah_mhs = new javax.swing.JMenu();
        sm_pribadi = new javax.swing.JMenuItem();
        sm_ortu = new javax.swing.JMenuItem();
        menu_akademik_mhs = new javax.swing.JMenu();
        menu_tampil_jadwal = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        header_mhs.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        header_mhs.setText("SAKTI");
        jPanel1.add(header_mhs, new java.awt.GridBagConstraints());

        panelinduk_mhs.setLayout(new java.awt.CardLayout());

        border.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        input_mhs.setLayout(new java.awt.GridLayout(8, 2, 0, 15));

        jLabel5.setText("NRP");
        input_mhs.add(jLabel5);

        txt_NRP.setEditable(false);
        txt_NRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NRPActionPerformed(evt);
            }
        });
        input_mhs.add(txt_NRP);

        jLabel12.setText("Email");
        input_mhs.add(jLabel12);

        txt_Email_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Email_mhsActionPerformed(evt);
            }
        });
        input_mhs.add(txt_Email_mhs);

        jLabel6.setText("Nama");
        input_mhs.add(jLabel6);

        txt_Nama_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nama_mhsActionPerformed(evt);
            }
        });
        input_mhs.add(txt_Nama_mhs);

        jLabel9.setText("Jenis Kelamin");
        input_mhs.add(jLabel9);

        pnl_jk_mhs.setLayout(new java.awt.GridLayout());

        ls_jk.add(rd_laki_mhs);
        rd_laki_mhs.setText("Laki-laki");
        pnl_jk_mhs.add(rd_laki_mhs);

        ls_jk.add(rd_perempuan_mhs);
        rd_perempuan_mhs.setText("Perempuan");
        pnl_jk_mhs.add(rd_perempuan_mhs);

        input_mhs.add(pnl_jk_mhs);

        jLabel10.setText("Agama");
        input_mhs.add(jLabel10);

        cbx_Agama_mhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "Islam", "Kristen", "Katholik", "Hindu", "Budha", "Konghucu" }));
        input_mhs.add(cbx_Agama_mhs);

        jLabel11.setText("Alamat");
        input_mhs.add(jLabel11);

        txt_Alamat_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Alamat_mhsActionPerformed(evt);
            }
        });
        input_mhs.add(txt_Alamat_mhs);

        jLabel15.setText("Kota");
        input_mhs.add(jLabel15);

        cbx_kota_mhs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "===PILIH===", "Malang", "Surabaya", "Blitar", "Kediri", "Probolinggo", "Lamongan", "Lumajang" }));
        input_mhs.add(cbx_kota_mhs);

        jLabel21.setText("No Hp");
        input_mhs.add(jLabel21);

        txt_nohp_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nohp_mhsActionPerformed(evt);
            }
        });
        input_mhs.add(txt_nohp_mhs);

        javax.swing.GroupLayout borderLayout = new javax.swing.GroupLayout(border);
        border.setLayout(borderLayout);
        borderLayout.setHorizontalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        borderLayout.setVerticalGroup(
            borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
            .addGroup(borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(borderLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnUbah_mhs.setText("Ubah Data");
        btnUbah_mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah_mhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_mhsLayout = new javax.swing.GroupLayout(panel_mhs);
        panel_mhs.setLayout(panel_mhsLayout);
        panel_mhsLayout.setHorizontalGroup(
            panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mhsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mhsLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(btnUbah_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        panel_mhsLayout.setVerticalGroup(
            panel_mhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mhsLayout.createSequentialGroup()
                .addComponent(border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUbah_mhs)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_mhs, "cv_pribadi");

        border1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Orang Tua Mahasiswa"));

        input_ortu.setLayout(new java.awt.GridLayout(7, 2, 0, 15));

        jLabel13.setText("Nama Ayah");
        input_ortu.add(jLabel13);

        txtnm_ayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnm_ayahActionPerformed(evt);
            }
        });
        input_ortu.add(txtnm_ayah);

        jLabel14.setText("No KTP Ayah");
        input_ortu.add(jLabel14);

        txtktp_ayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtktp_ayahActionPerformed(evt);
            }
        });
        input_ortu.add(txtktp_ayah);

        jLabel16.setText("Nama Ibu");
        input_ortu.add(jLabel16);

        txtnm_ibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnm_ibuActionPerformed(evt);
            }
        });
        input_ortu.add(txtnm_ibu);

        jLabel17.setText("No KTP Ibu");
        input_ortu.add(jLabel17);

        txtktp_ibu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtktp_ibuActionPerformed(evt);
            }
        });
        input_ortu.add(txtktp_ibu);

        jLabel18.setText("Alamat Orang Tua");
        input_ortu.add(jLabel18);

        txt_alamatortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatortuActionPerformed(evt);
            }
        });
        input_ortu.add(txt_alamatortu);

        jLabel20.setText("Kota Orang Tua");
        input_ortu.add(jLabel20);

        cb_kota_ortu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== KOTA ===" }));
        input_ortu.add(cb_kota_ortu);

        jLabel19.setText("Telp Orang Tua");
        input_ortu.add(jLabel19);

        txt_telp_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telp_ortuActionPerformed(evt);
            }
        });
        input_ortu.add(txt_telp_ortu);

        javax.swing.GroupLayout border1Layout = new javax.swing.GroupLayout(border1);
        border1.setLayout(border1Layout);
        border1Layout.setHorizontalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_ortu, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        border1Layout.setVerticalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
            .addGroup(border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(border1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnUbah_ortu.setText("Ubah Data");
        btnUbah_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah_ortuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ortuLayout = new javax.swing.GroupLayout(panel_ortu);
        panel_ortu.setLayout(panel_ortuLayout);
        panel_ortuLayout.setHorizontalGroup(
            panel_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ortuLayout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(btnUbah_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panel_ortuLayout.setVerticalGroup(
            panel_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(border1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUbah_ortu)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_ortu, "cv_ortu");

        TabelMatkul_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Periode", "Kode", "Nama Matkul", "Nama Dosen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TabelMatkul_mhs);

        javax.swing.GroupLayout panel_matkulLayout = new javax.swing.GroupLayout(panel_matkul);
        panel_matkul.setLayout(panel_matkulLayout);
        panel_matkulLayout.setHorizontalGroup(
            panel_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        panel_matkulLayout.setVerticalGroup(
            panel_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_matkulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelinduk_mhs.add(panel_matkul, "cv_matkul");

        panel_tmpl_pribadi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Data Pribadi Mahasiswa")));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        jPanel3.setLayout(new java.awt.GridLayout(8, 2, 0, 15));

        jLabel1.setText("Nama Lengkap");
        jPanel3.add(jLabel1);

        lbl_tmpl_nama_mhs.setText("Nama Lengkap");
        jPanel3.add(lbl_tmpl_nama_mhs);

        jLabel3.setText("NRP");
        jPanel3.add(jLabel3);

        lbl_tmpl_nrp_mhs.setText("NRP");
        jPanel3.add(lbl_tmpl_nrp_mhs);

        jLabel2.setText("Program Studi");
        jPanel3.add(jLabel2);

        lbl_tmpl_prodi_mhs.setText("Program Studi");
        jPanel3.add(lbl_tmpl_prodi_mhs);

        jLabel4.setText("Status Masuk");
        jPanel3.add(jLabel4);

        lbl_tmpl_stts_msuk_mhs.setText("Status Masuk");
        jPanel3.add(lbl_tmpl_stts_msuk_mhs);

        jLabel22.setText("Agama");
        jPanel3.add(jLabel22);

        lbl_tmpl_agama_mhs.setText("Agama");
        jPanel3.add(lbl_tmpl_agama_mhs);

        jLabel23.setText("Jenis Kelamin");
        jPanel3.add(jLabel23);

        lbl_tmpl_jk_mhs.setText("Jenis Kelamin");
        jPanel3.add(lbl_tmpl_jk_mhs);

        jLabel24.setText("Tempat / Tanggal Lahir");
        jPanel3.add(jLabel24);

        lbl_tmpl_ttl_mhs.setText("Tempat / Tanggal Lahir");
        jPanel3.add(lbl_tmpl_ttl_mhs);

        jLabel25.setText("No Hp");
        jPanel3.add(jLabel25);

        lbl_tmpl_no_mhs.setText("No Hp");
        jPanel3.add(lbl_tmpl_no_mhs);

        javax.swing.GroupLayout panel_tmpl_pribadiLayout = new javax.swing.GroupLayout(panel_tmpl_pribadi);
        panel_tmpl_pribadi.setLayout(panel_tmpl_pribadiLayout);
        panel_tmpl_pribadiLayout.setHorizontalGroup(
            panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_pribadiLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_tmpl_pribadiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_tmpl_pribadiLayout.setVerticalGroup(
            panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_pribadiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(panel_tmpl_pribadiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tmpl_pribadiLayout.createSequentialGroup()
                    .addContainerGap(210, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        panelinduk_mhs.add(panel_tmpl_pribadi, "cv_tmpl_pribadi");

        panel_tmpl_ortu.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Orang Tua Mahasiswa"));

        jPanel2.setLayout(new java.awt.GridLayout(7, 2, 0, 15));

        jLabel28.setText("Nama Ayah");
        jPanel2.add(jLabel28);

        lbl_tmpl_nm_ayah_mhs.setText("Nama Ayah");
        jPanel2.add(lbl_tmpl_nm_ayah_mhs);

        jLabel26.setText("Nomor KTP Ayah");
        jPanel2.add(jLabel26);

        lbl_tmpl_ktp_ayah_mhs.setText("Nomor KTP Ayah");
        jPanel2.add(lbl_tmpl_ktp_ayah_mhs);

        jLabel27.setText("Nama Ibu\t");
        jPanel2.add(jLabel27);

        lbl_tmpl_nm_ibu_mhs.setText("Nama Ibu\t");
        jPanel2.add(lbl_tmpl_nm_ibu_mhs);

        jLabel29.setText("Nomor KTP Ibu");
        jPanel2.add(jLabel29);

        lbl_tmpl_ktp_ibu_mhs.setText("Nomor KTP Ibu");
        jPanel2.add(lbl_tmpl_ktp_ibu_mhs);

        jLabel30.setText("Telepon Orang Tua");
        jPanel2.add(jLabel30);

        lbl_tmpl_telp_ortu_mhs.setText("Telepon Orang Tua");
        jPanel2.add(lbl_tmpl_telp_ortu_mhs);

        jLabel31.setText("Alamat Orang Tua");
        jPanel2.add(jLabel31);

        lbl_tmpl_almt_ortu_mhs.setText("Alamat Orang Tua");
        jPanel2.add(lbl_tmpl_almt_ortu_mhs);

        jLabel32.setText("Kota Orang Tua");
        jPanel2.add(jLabel32);

        lbl_tmpl_kota_ortu_mhs.setText("Kota Orang Tua");
        jPanel2.add(lbl_tmpl_kota_ortu_mhs);

        javax.swing.GroupLayout panel_tmpl_ortuLayout = new javax.swing.GroupLayout(panel_tmpl_ortu);
        panel_tmpl_ortu.setLayout(panel_tmpl_ortuLayout);
        panel_tmpl_ortuLayout.setHorizontalGroup(
            panel_tmpl_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_tmpl_ortuLayout.setVerticalGroup(
            panel_tmpl_ortuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tmpl_ortuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        panelinduk_mhs.add(panel_tmpl_ortu, "cv_tmpl_ortu");

        menu_beranda_mhs.setText("Profile");

        sm_tmpl_pribadi.setText("Tampil Data Pribadi");
        sm_tmpl_pribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_tmpl_pribadiActionPerformed(evt);
            }
        });
        menu_beranda_mhs.add(sm_tmpl_pribadi);

        sm_tmpl_ortu.setText("Tampil Data Orang Tua");
        sm_tmpl_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_tmpl_ortuActionPerformed(evt);
            }
        });
        menu_beranda_mhs.add(sm_tmpl_ortu);

        jMenuBar1.add(menu_beranda_mhs);

        menu_ubah_mhs.setText("Ubah Data");

        sm_pribadi.setText("Data Pribadi");
        sm_pribadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_pribadiActionPerformed(evt);
            }
        });
        menu_ubah_mhs.add(sm_pribadi);

        sm_ortu.setText("Orang Tua");
        sm_ortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sm_ortuActionPerformed(evt);
            }
        });
        menu_ubah_mhs.add(sm_ortu);

        jMenuBar1.add(menu_ubah_mhs);

        menu_akademik_mhs.setText("Akademik");

        menu_tampil_jadwal.setText("Jadwal");
        menu_tampil_jadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_tampil_jadwalActionPerformed(evt);
            }
        });
        menu_akademik_mhs.add(menu_tampil_jadwal);

        jMenuBar1.add(menu_akademik_mhs);

        menu_logout.setText("Logout");
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelinduk_mhs, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelinduk_mhs, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Alamat_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Alamat_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Alamat_mhsActionPerformed

    private void txt_Nama_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nama_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nama_mhsActionPerformed

    private void txt_NRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NRPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NRPActionPerformed

    private void txt_Email_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Email_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Email_mhsActionPerformed

    private void txtnm_ayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnm_ayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnm_ayahActionPerformed

    private void txtktp_ayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtktp_ayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtktp_ayahActionPerformed

    private void txtnm_ibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnm_ibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnm_ibuActionPerformed

    private void txtktp_ibuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtktp_ibuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtktp_ibuActionPerformed

    private void txt_alamatortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatortuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatortuActionPerformed

    private void txt_telp_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telp_ortuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telp_ortuActionPerformed

    private void txt_nohp_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nohp_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nohp_mhsActionPerformed
    
    //untuk pindah ke halaman ubah data ortu
    private void sm_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_ortuActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_ortu");
        header_mhs.setText("UBAH DATA ORANG TUA");
    }//GEN-LAST:event_sm_ortuActionPerformed

    //untuk pindah ke halaman ubah data pribadi
    private void sm_pribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_pribadiActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_pribadi");
        header_mhs.setText("UBAH DATA PRIBADI");
    }//GEN-LAST:event_sm_pribadiActionPerformed

    private void btnUbah_mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah_mhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbah_mhsActionPerformed

    private void btnUbah_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah_ortuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbah_ortuActionPerformed

    private void sm_tmpl_pribadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_tmpl_pribadiActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_pribadi");
        header_mhs.setText("PROFILE MAHASISWA");
    }//GEN-LAST:event_sm_tmpl_pribadiActionPerformed

    private void sm_tmpl_ortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sm_tmpl_ortuActionPerformed
       CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_tmpl_ortu");
        header_mhs.setText("PROFILE ORANG TUA");
    }//GEN-LAST:event_sm_tmpl_ortuActionPerformed

    private void menu_tampil_jadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_tampil_jadwalActionPerformed
        CardLayout cview = (CardLayout) panelinduk_mhs.getLayout();
        cview.show(panelinduk_mhs, "cv_matkul");
        header_mhs.setText("JADWAL");
    }//GEN-LAST:event_menu_tampil_jadwalActionPerformed

    private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
        new framelogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu_logoutMouseClicked
    
    //untuk menampilkan kota
    private void tampilkota(){
        cb_kota_ortu.removeAllItems();
        cb_kota_ortu.addItem("=== KOTA ===");
        
        try{
            String db_tmplkota_ortu = "SELECT * FROM kota";
            PreparedStatement  ps_tmpl_kota = con.prepareStatement(db_tmplkota_ortu);
            ResultSet rs_tmplkota_ortu = ps_tmpl_kota.executeQuery();

            while(rs_tmplkota_ortu.next()){
                cb_kota_ortu.addItem(">  "+rs_tmplkota_ortu.getString("Kota"));
                
                kota_ortu_mhs = hapus_tanda(cb_kota_ortu.getSelectedItem().toString());
            } 
        }
        catch(Exception e){
            
        }
        
    }
    
    //untuk menghapus tanda ">"
    private String hapus_tanda(String str){
        return str.substring(2);
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framemahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framemahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelMatkul_mhs;
    private javax.swing.JPanel border;
    private javax.swing.JPanel border1;
    private javax.swing.JButton btnUbah_mhs;
    private javax.swing.JButton btnUbah_ortu;
    private javax.swing.JComboBox<String> cb_kota_ortu;
    private javax.swing.JComboBox<String> cbx_Agama_mhs;
    private javax.swing.JComboBox<String> cbx_kota_mhs;
    private javax.swing.JLabel header_mhs;
    private javax.swing.JPanel input_mhs;
    private javax.swing.JPanel input_ortu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_tmpl_agama_mhs;
    private javax.swing.JLabel lbl_tmpl_almt_ortu_mhs;
    private javax.swing.JLabel lbl_tmpl_jk_mhs;
    private javax.swing.JLabel lbl_tmpl_kota_ortu_mhs;
    private javax.swing.JLabel lbl_tmpl_ktp_ayah_mhs;
    private javax.swing.JLabel lbl_tmpl_ktp_ibu_mhs;
    private javax.swing.JLabel lbl_tmpl_nama_mhs;
    private javax.swing.JLabel lbl_tmpl_nm_ayah_mhs;
    private javax.swing.JLabel lbl_tmpl_nm_ibu_mhs;
    private javax.swing.JLabel lbl_tmpl_no_mhs;
    private javax.swing.JLabel lbl_tmpl_nrp_mhs;
    private javax.swing.JLabel lbl_tmpl_prodi_mhs;
    private javax.swing.JLabel lbl_tmpl_stts_msuk_mhs;
    private javax.swing.JLabel lbl_tmpl_telp_ortu_mhs;
    private javax.swing.JLabel lbl_tmpl_ttl_mhs;
    private javax.swing.ButtonGroup ls_jk;
    private javax.swing.JMenu menu_akademik_mhs;
    private javax.swing.JMenu menu_beranda_mhs;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JMenuItem menu_tampil_jadwal;
    private javax.swing.JMenu menu_ubah_mhs;
    private javax.swing.JPanel panel_matkul;
    private javax.swing.JPanel panel_mhs;
    private javax.swing.JPanel panel_ortu;
    private javax.swing.JPanel panel_tmpl_ortu;
    private javax.swing.JPanel panel_tmpl_pribadi;
    private javax.swing.JPanel panelinduk_mhs;
    private javax.swing.JPanel pnl_jk_mhs;
    private javax.swing.JRadioButton rd_laki_mhs;
    private javax.swing.JRadioButton rd_perempuan_mhs;
    private javax.swing.JMenuItem sm_ortu;
    private javax.swing.JMenuItem sm_pribadi;
    private javax.swing.JMenuItem sm_tmpl_ortu;
    private javax.swing.JMenuItem sm_tmpl_pribadi;
    private javax.swing.JTextField txt_Alamat_mhs;
    private javax.swing.JTextField txt_Email_mhs;
    private javax.swing.JTextField txt_NRP;
    private javax.swing.JTextField txt_Nama_mhs;
    private javax.swing.JTextField txt_alamatortu;
    private javax.swing.JTextField txt_nohp_mhs;
    private javax.swing.JTextField txt_telp_ortu;
    private javax.swing.JTextField txtktp_ayah;
    private javax.swing.JTextField txtktp_ibu;
    private javax.swing.JTextField txtnm_ayah;
    private javax.swing.JTextField txtnm_ibu;
    // End of variables declaration//GEN-END:variables
}
